### ISSUE TITLE
Enhancement: Add support for translations

### ISSUE THREAD

**Issue by ciotlosm** [yllibed/Zigbee2MqttAssistant#100]
Add support for translations. Maybe something similar to home assistant. I'm happy to contribute one translation set.

**Comment by carldebilly** [comment]
That would be a nice idea.
I'm french speaking, so I can make the french version :-)

@all-contributors please add ciotlosm to ideas

**Comment by carldebilly** [comment]
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/localization?view=aspnetcore-3.0
