### ISSUE TITLE
dev-branch 0.3.92: error renaming devices

### ISSUE THREAD

**Issue by pejotigrek** [yllibed/Zigbee2MqttAssistant#102]
after trying to rename one new device all I got is:
![image](https://user-images.githubusercontent.com/10796588/67814158-a2d51e80-faa3-11e9-8651-46d921891bee.png)

of course name stays unchanged.

**Comment by carldebilly** [comment]
I need more information to diagnose this problem...
* Version of Z2MA
* Version of Z2M
* Type of installation (docker or HASS.IO) + CPU
* Logs, if possibe
* The names (current name & the one you're trying to set)

**Comment by pejotigrek** [comment]
- Z2MA version: 0.3.92 [dev]
- Z2M version: 1.6.0
- installation: HASS.IO @ RPi3
- I've checked the Z2M logs earlier and saw only info that "error renaming device", now even that is gone
- names: original was `0x00158d000358d83f` [auto discovered] and I tried to change it to `sns_guestroom` [my naming scheme - _sns_ for "sensor" and location of the sensor.

in the meantime I was trying to find a workaround and it looks like Z2MA didn't got it's permissions to write config this time. earlier, when I renamed devices, new names were written to `\zigbee2mqtt\devices.yaml` under the _friendly_name_ attribute of the sensor. this time it stayed untouched. after I stopped Z2M, manually changed _friendly_name_ and started Z2M again, new name appeared in Z2MA dashboard. maybe that would help?

I'm at work right now, if the above doesn't help, I can play with changing the names after I'm back at home [in the evening probably]. just tell me what logs then you'll need if the error would be persistent.

**Comment by carldebilly** [comment]
You'll need to try again and get the log from Z2M...

**Comment by pejotigrek** [comment]
I'm starting to regret that I didn't thought about keeping the whole log for the first time :(
I can't reproduce the issue now.. I probably should be happy that all is working - but with that said, the issue will remain a mystery..

for the few past days I tried to rename this or that device and.. it always did work.

few new sensors are on their way to me from aliexpress. I hope they'll come soon and I'll try the whole process again. maybe with unknown devices it will show up again.

I guess that if you want to  - please close this issue, I'll comment here again if new devices will bring the issue and you'll decide if it needs to be reopened.

**Comment by carldebilly** [comment]
Reopen it as required...!
@all-contributors please add pejotigrek to bugs
