### ISSUE TITLE
Request - Built in log viewer for z2m's log file(s)

### ISSUE THREAD

**Issue by skawt-tee** [yllibed/Zigbee2MqttAssistant#121]
**Is your feature request related to a problem? Please describe.**

z2ma is turning into a fantastic tool for managing z2m in HA (love the network map!). To further this, it would be great if we had the ability to tail z2m's log file directly within the z2ma interface, instead of having to mash the refresh button under the z2m addon page, or tailing directly under SSH.

**Describe the solution you'd like**
This addon has a built-in tail/log viewer that is a good example of what I'm looking for:
hassio_google_drive_backup (https://github.com/sabeechen/hassio-google-drive-backup)

You could extend it a bit by allowing us to switch the log level within the logview interface (although its easy enough to do from z2ma settings.

**Comment by carldebilly** [comment]
I agree it would be very great to have this. Somebody already asked this (#36). The problem is more there's no easy was to extract those logs because it's from another container.

Are you using it as a HASS.IO add-in or a stand alone container?  Maybe it's possible to connect to HASS.IO to get those logs...  I should check.

**Comment by carldebilly** [comment]
+ as specified in https://github.com/yllibed/Zigbee2MqttAssistant/issues/163, it would be nice to have a per-device log.

**Comment by carldebilly** [comment]
The plan right now:
* Add the logging-to-mqtt feature into Z2M (create a PR for that)
* Add an in-memory logging feature (retaining a configureable number of lines)
* Implement a log page, communication in real time with back-end using a streaming mecanism (SignalR?)
* Implement a log viewer.  Maybe using Prismjs (as mentionned there: https://github.com/yllibed/Zigbee2MqttAssistant/issues/36#issuecomment-585222651)

@magpern

**Comment by carldebilly** [comment]
Will be closed and follow under #36.

**Comment by carldebilly** [comment]
Don't forget https://github.com/yllibed/Zigbee2MqttAssistant/issues/121#issuecomment-592974427
