### ISSUE TITLE
Cannot connect to the server

### ISSUE THREAD

**Issue by jcsogo** [yllibed/Zigbee2MqttAssistant#124]
I have installed Z2MA in docker. Once configured, I run docker and forward por 80 to 8081. I cannot connect into that port when trying.

This is my docker command:
docker run -p 8881:80 \
 --name zigbee-assistant \
 -e Z2MA_SETTINGS__MQTTSERVER=X.X.X.X \
 -e Z2MA_SETTINGS__MQTTUSERNAME= \
 -e Z2MA_SETTINGS__MQTTPASSWORD= \
 --restart unless-stopped \
 carldebilly/zigbee2mqttassistant

## Installation
 - Version of Zigbee2Mqtt: 1.7.0 (docker)
 - Version of Zigbee2MqttAssistant: 0.3.105
 - Installation type (HASS.IO, Docker...): docker
 - Docker version + CPU type (amd64, arm arm64...): arm

## Pertinent logs
Starting Zigbee2MqttAssistant v0.3.105+Branch.master.Sha.b1c45d4ca947b2701c12bdf7d0e8be4083a0a2fe...
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {738fea38-5861-4329-9761-49b99125d0df} may be persisted to storage in unencrypted form.
Hosting environment: Production
Content root path: /app
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.

**Comment by carldebilly** [comment]
According to your command line, it's the port `8881`, not `8081`.

Reopen this issue if you think the problem is something else.

Thanks for using Zigbee2MqttAssistant!
