### ISSUE TITLE
Delete and Bind not working

### ISSUE THREAD

**Issue by james-fry** [yllibed/Zigbee2MqttAssistant#13]
Hi.

Firstly nice project! :)

For me, deleting devices does not work.
I get a message like this:

The webpage at https://xxxxx.com/api/hassio_ingress/i-2pGkEiydrXBLXufVU8Mip29vIClOCT0yCO2TnDbX0/Home/RemoveDevice/Boiler%20Leak%20Detector might be temporarily down or it may have moved permanently to a new web address.

Is delete a WIP?

**Comment by carldebilly** [comment]
It works for me here.  Are you getting this error immediatly or after a timeout?  I think that's the 60 seconds timeout of the HASS-IO ingress.

All this all is a WIP anyway ;-)  But all features are tested to work on my lab and my production before being published.

**Comment by james-fry** [comment]
The error is immediate, not after time out.
I did the following to test:

1) restarted the addon
2) opened Zigbee2MqttAssistant GUI

BTW when I open UI I get log:
_warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect._

3) I triggered this issue with delete
4) checked the server log in hassio addon page but I dont see any error logged

**Comment by james-fry** [comment]
I will update with logs (or confirmtion of no logs) asap later today.
BTW I have tried a bind and that also failed with same type of error.

**Comment by james-fry** [comment]
I checked and I dont get debug log entry in zigbee2mqtt log.
Actually I dont get any MQTT message to my broker for bind.
(I used an mqtt client to watch the zigbee2mqtt/bridge/# topic for bind messages.

So looks like Zigbee2MqttAssistant is not able to send the mqtt bind message to my broker.
BTW broker is mosquitto from the hassio commuinity addon "MQTT Server & Web client"

**Comment by james-fry** [comment]
BTW if I send a bind request from another mqtt client I get the following in the z2m log:

  zigbee2mqtt:debug 8/28/2019, 6:01:20 PM Received MQTT message on 'zigbee2mqtt/bridge/bind/Ikea Square Switch' with data 'Garden Switch'
  zigbee2mqtt:debug 8/28/2019, 6:01:20 PM binding cluster '6' from '0x000d6ffffede76b0' (1) to '0x000b57fffeef91a5'
  zigbee2mqtt:debug 8/28/2019, 6:01:20 PM binding cluster '8' from '0x000d6ffffede76b0' (1) to '0x000b57fffeef91a5'
  zigbee2mqtt:debug 8/28/2019, 6:01:20 PM Binding  'Ikea Square Switch' - 6

...but actually the binding fails it seems :(

**Comment by james-fry** [comment]
Just to confirm that delete is still not working on the latest release.
is there any way to enable debug logging in z2massistant?

To confirm, this is not a critial issue for me - I can use mqtt client to inject the delete requests.
but happy to help debug this...

**Comment by carldebilly** [comment]
**DELETE PROBLEM**: Does it work after restarting Z2MA ? No there's currently no useful "debug log".  Maybe I should add some...  Do you have the Z2M log for this problem?

**BINDING PROBLEM**: Your timeout while binding the Ikea device is probably because you need to manipulate it during the binding process.

**Comment by cor-vo** [comment]
Same here, but it looks like it only occurs when using a domain name. 
It works like it should when i go to the page through the direct IP address.

**Comment by james-fry** [comment]
Ah nice find with the domain vs IP.
I always use domain and https.

**Comment by carldebilly** [comment]
@all-contributors please add james-fry to bugs

**Comment by james-fry** [comment]
Just commenting that I tried again to delete a device on the latest version (0.2.0-dev.153) and I still have the issue. I am using hassio ingress so I cannot check without using domainname since the port is not mapped outside of docker.

**Comment by carldebilly** [comment]
Maybe it will be fixed with #107

**Comment by carldebilly** [comment]
@james-fry Support for `force_remove` has been implemented now.

**Comment by EpicLPer** [comment]
I'm still getting this issue right now. Whenever I try to do something that seems to "send" something to the addon (triggering a scan, rename, delete, etc.) it'll instantly error out with the same text as the first text mentioned.

**Comment by james-fry** [comment]
Same for me - still get the error for delete/bind.
Using own domain, https, reverse proxy (nginx)

**Comment by redpizza69** [comment]
> I'm still getting this issue right now. Whenever I try to do something that seems to "send" something to the addon (triggering a scan, rename, delete, etc.) it'll instantly error out with the same text as the first text mentioned.

Same with me.

**Comment by redpizza69** [comment]
A year on and still no-one has a solution?

**Comment by czachor** [comment]
Same here.
