### ISSUE TITLE
[BUG] Zigbee Id is empty in status page

### ISSUE THREAD

**Issue by wojciechczyz** [yllibed/Zigbee2MqttAssistant#134]
# Describe the bug

Coordinator Zigbee Id: is not displayed, device works fine
## To Reproduce

1. Go to Status screen
4. See Coordinator Zigbee Id: is empty

**Expected behavior**

Id should be displayed
## Steps I took to try resolve the problem

Yes latest version
## Installation
 Version of Zigbee2MqttAssistant (this software): 0.3.105 (0.3.105+Branch.master.Sha.b1c45d4ca947b2701c12bdf7d0e8be4083a0a2fe) Release
Version of Zigbee2Mqtt: 1.7.1 
Coordinator version: 20190619

**Comment by carldebilly** [comment]
Is it just for the coordinator or any devices?

**Comment by carldebilly** [comment]
This PR may fix the problem https://github.com/yllibed/Zigbee2MqttAssistant/pull/148

**Comment by carldebilly** [comment]
Z2MA v`0.3.122`. Check on the "dev" channel.
