### ISSUE TITLE
Help with installing

### ISSUE THREAD

**Issue by Roeliooo** [yllibed/Zigbee2MqttAssistant#139]
Hi All,

Can somebody help me with installing ? I just installed Docker and works fine. Now I want to load Zigbee2MqttAssistant. But have a few questions.
1. I don't have password and username. What to fill in ?
2. Mqtt is running on localhost. What to fill in ?

**Comment by carldebilly** [comment]
Zigbee2MqttAssistant is _just_ a GUI to connect with Zigbee2Mqtt to provide an overview of the system. You need to connect to your MQTT server. Those username & password are those of your MQTT Broker.
