### ISSUE TITLE
Passwords containing "!tto" in docker command display error - !tt0: event not found

### ISSUE THREAD

**Issue by rosscullen** [yllibed/Zigbee2MqttAssistant#149]
Passwords containing "!tt0" in docker command display error - !tt0: event not found
Not sure if its because its the word tt0 or because it doesn't like characters in general. Hope this is of some use!

**Comment by carldebilly** [comment]
With HASS.IO or just docker? Please give me more context to help you... config samples, etc....

**Comment by rosscullen** [comment]
Using latest version of Home Assistant 0.103.

Running HA in Docker on synology.

`docker run \
--net=host \
-p 8880:8888 \
--name="zigbee2mqtt-assistant" \
-e Z2MA_SETTINGS__MQTTSERVER=nas.local \
-e Z2MA_SETTINGS__MQTTUSERNAME=mqttuser \
-e Z2MA_SETTINGS__MQTTPASSWORD=mosqu!tt0 \
-e PGID=65537 \
-e PUID=1029 \
-e TZ=Europe/London \
--restart unless-stopped \
carldebilly/zigbee2mqttassistant`

The command interupts after the password line with the error:
`command display error - !tt0: event not found`

Hope this makes sense!

**Comment by carldebilly** [comment]
Try that instead:
```
`docker run \
--net=host \
-p 8880:8888 \
--name="zigbee2mqtt-assistant" \
-e "Z2MA_SETTINGS__MQTTSERVER=nas.local" \
-e "Z2MA_SETTINGS__MQTTUSERNAME=mqttuser" \
-e "Z2MA_SETTINGS__MQTTPASSWORD=mosqu!tt0" \
-e PGID=65537 \
-e PUID=1029 \
-e TZ=Europe/London \
--restart unless-stopped \
carldebilly/zigbee2mqttassistant`
```

**Comment by rosscullen** [comment]
Perfect! Works like a charm! I've a seperate issue which I will post shortly but many thanks for your help on that!

**Comment by carldebilly** [comment]
I just updated the documentation to prevent this problem from happening again.
