### ISSUE TITLE
Unable to start in Docker - "http://[::]:80: address already in use."

### ISSUE THREAD

**Issue by rosscullen** [yllibed/Zigbee2MqttAssistant#151]
# Describe the bug
Getting the following error on Synology docker:
`crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
System.IO.IOException: Failed to bind to address http://[::]:80: address already                                                                                         in use.`

Docker command as follows:
```
docker run \
--net=host \
-p 8880:8888 \
--name="zigbee2mqtt-assistant" \
-e "Z2MA_SETTINGS__MQTTSERVER=nas.local" \
-e "Z2MA_SETTINGS__MQTTUSERNAME=mqttuser" \
-e "Z2MA_SETTINGS__MQTTPASSWORD=mosqu!tt0" \
-e PGID=65537 \
-e PUID=1029 \
-e TZ=Europe/London \
--restart unless-stopped \
carldebilly/zigbee2mqttassistant
```

Port 80 is already in use by ngix & webstation by default on Synology DSM.

## Installation
 - Version of Zigbee2Mqtt: latest (as of 01/2020)
 - Version of Zigbee2MqttAssistant: latest (as of 01/2020)
 - Installation type (HASS.IO, Docker...):  Home Assistant on Docker using Synology DSM 6.2
 - Docker version + CPU type (amd64, arm arm64...): amd64

**Comment by carldebilly** [comment]
It's because you're using the `--net=host` mode. If you expect _kestrel_ (the netcore web server) to open its port on `8888`, you need to tel it to do so.  So here's the right way to do it (also described in this issue: https://github.com/yllibed/Zigbee2MqttAssistant/issues/67)

```
docker run \
--net=host \
--name="zigbee2mqtt-assistant" \
-e "Z2MA_SETTINGS__MQTTSERVER=nas.local" \
-e "Z2MA_SETTINGS__MQTTUSERNAME=mqttuser" \
-e "Z2MA_SETTINGS__MQTTPASSWORD=mosqu!tt0" \
-e "ASPNETCORE_URLS=https://*:8888" \
-e PGID=65537 \
-e PUID=1029 \
-e TZ=Europe/London \
--restart unless-stopped \
carldebilly/zigbee2mqttassistant
```

(you also need to remove the `-p` parameter since you're binding the port directly on the host)
