### ISSUE TITLE
Device specific log

### ISSUE THREAD

**Issue by twsI** [yllibed/Zigbee2MqttAssistant#163]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd love to see the log related to only the selected device. Having this option would be really cool.

**Describe alternatives you've considered**
Checking the zigbee2mqtt log manually

**Comment by carldebilly** [comment]
A change is required in Z2M for that. I'm seriously considering creating a PR for that. There's already this issue opened: https://github.com/yllibed/Zigbee2MqttAssistant/issues/121

I'll close yours and add the "per device" as a requirement to issue #121.
