### ISSUE TITLE
Is x86 support planned?

### ISSUE THREAD

**Issue by noidkn** [yllibed/Zigbee2MqttAssistant#165]
Good afternoon!
Is x86 support planned?

**Comment by carldebilly** [comment]
That's a good question. Why do you need this platform? Officially _dotnet core_ doesn't support `x86`: https://docs.microsoft.com/en-us/dotnet/core/install/dependencies?tabs=netcore30&pivots=os-linux

Maybe you can try to run the `ARM32` version using QEMU. https://www.balena.io/blog/building-arm-containers-on-any-x86-machine-even-dockerhub/

**Comment by noidkn** [comment]
Thanks for the detailed answer.

**Comment by MarcusUA** [comment]
> Why do you need this platform? 
in some case we have to stick with x86 - my mini server has older Intel Atom, that doesn't support x64 (technically cpu does support it, but its motherboard was not updated to support), so I had to use Ubuntu 16 x86 to run Hassio.

> Maybe you can try to run the `ARM32` version using QEMU. https://www.balena.io/blog/building-arm-containers-on-any-x86-machine-even-dockerhub/
will try that, but it would be really great if there was how-to in FAQ for this project.
Anyways, that you so much to it!
