### ISSUE TITLE
[BUG]unable to connect to mqtt server

### ISSUE THREAD

**Issue by sander816** [yllibed/Zigbee2MqttAssistant#168]
i don't know what i am doing wrong here, but i keep getting

`
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {50c14688-1108-4ad4-84c4-ea874b83fc7f} may be persisted to storage in unencrypted form.
Hosting environment: Production
Content root path: /app
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to connect to MQTT server 127.0.0.1.
MQTTnet.Exceptions.MqttCommunicationException: Connection refused [::ffff:127.0.0.1]:1883
`
starting docker with this command
tried various versions of Z2MA_SETTINGS__MQTTSERVER. i have no user or pass set
`sudo docker run -p 8880:80 -e "Z2MA_SETTINGS__MQTTSERVER=127.0.0.1" -e "Z2MA_SETTINGS__MQTTPORT=1883" -e "Z2MA_SETTINGS__MQTTUSERNAME=" -e "Z2MA_SETTINGS__MQTTPASSWORD=" --restart unless-stopped carldebilly/zigbee2mqttassistant
`

**Comment by carldebilly** [comment]
You cannot use `127.0.0.1` because it will target the container itself and there's not MQTT server in the container.

You should replace this with the name of the MQTT server's container: Docker will resolve it to the right IP address on the internal network.

You may also try the `--net=host` mode if you still want to use `127.0.0.1`.

**Comment by marcgarciamarti** [comment]
I'm also pulling my hair out with this. I can't seem to be able to connect with the official Mosquitto add-on. Using the systemwide alias _core-mosquitto_ does not work either. Could anybody give me a hand?

**Comment by olylak** [comment]
Same issue:

MQTTnet.Exceptions.MqttCommunicationException: Connection refused [::ffff:172.20.0.4]:1883

For the Z2MA_SETTINGS__MQTTSERVER I'm using mosquitto container name. From the shell that name is resolved successfully.
