### ISSUE TITLE
Docker hub missing Arm64 on latest tag

### ISSUE THREAD

**Issue by mattheys** [yllibed/Zigbee2MqttAssistant#172]
Not a major issue but thought I would point it out, I'm pulling the dev branch instead and it appears to be working.

https://hub.docker.com/r/carldebilly/zigbee2mqttassistant/tags

**Comment by carldebilly** [comment]
Ooooh good catch!

**Comment by carldebilly** [comment]
Should be fixed now.  Thanks for reporting!
