### ISSUE TITLE
Zigbee2mqtt on Raspbian

### ISSUE THREAD

**Issue by jondiez** [yllibed/Zigbee2MqttAssistant#173]
Could you get a web interface for the correct operation and configuration of the devices and zigbee2mqtt?
Thanks

**Comment by carldebilly** [comment]
You mean for the _connect_ operation? You can set the "allow join" in the status page of the app.  Is it what you want?

**Comment by jondiez** [comment]
No, what would be good is to have a website dedicated to zigbee2mqtt to be able to rename, delete, add and configure all the devices that are added to the network.

**Comment by carldebilly** [comment]
You can install the dotnet dependencies, but to be honest it's a lot more trouble than just using the container.

You should consider installing docker on raspbian instead...
https://dev.to/rohansawant/installing-docker-and-docker-compose-on-the-raspberry-pi-in-5-simple-steps-3mgl
