### ISSUE TITLE
Feature: Issue touchlink factory reset

### ISSUE THREAD

**Issue by theFork** [yllibed/Zigbee2MqttAssistant#181]
I would like to be able to reset Philips Hue lights using the touchlink factory reset feature of z2m (see https://github.com/Koenkk/zigbee2mqtt/issues/2396)

The solution I would like to have would be a button labeled "Touchlink reset" on the status tab that sends a MQTT message to `zigbee2mqtt/bridge/config/touchlink/factory_reset` with an empty payload.

It would also be really nice to get some kind of feedback that z2m has acknowledged the command.

**Comment by carldebilly** [comment]
That would be a nice improvement. Are you interested to code it? ;-)

**Comment by theFork** [comment]
I'm afraid this would exceed my skills and time budget. But I have some devices to test this :)

**Comment by magpern** [comment]
@carldebilly I could take a bit at this if you'd like?

**Comment by carldebilly** [comment]
@magpern That would be wonderful :-)

**Comment by magpern** [comment]
@theFork @carldebilly Is this good?
![image](https://user-images.githubusercontent.com/6589760/75636775-f4dcab00-5c21-11ea-96b7-c37c6a6ade8d.png)

I have not been able to test it in real life. I don't have any Hue lights, only IKEA lights. However, I see in the Z2M logs that stuff is happening, so in theory, if Z2M works, this should work.

Unfortunately, Z2M does not produce any MQTT logs for the TouchLink process, only regular logs which are not reachable by Z2MAssistant. So there is no way for Z2MA to know if the process starts or has finished or failed.

**Comment by carldebilly** [comment]
We should push a PR to Z2M to add logging as it were done for OTA ugprade (ref: https://github.com/Koenkk/zigbee2mqtt/pull/2936#discussion_r378484005).

**Comment by magpern** [comment]
@carldebilly 
> We should push a PR to Z2M to add logging as it were done for OTA ugprade 
Done!
