### ISSUE TITLE
Error om startup (binding)

### ISSUE THREAD

**Issue by tabnul** [yllibed/Zigbee2MqttAssistant#189]
I just installed the application, my zigbee2mqtt allready had a binding and this device gives an error.
Dont know what the effect is, but apparently the application is unable to parse the existing (working) binding. 
Binding does not showup in the GUI either.

## Screenshots
screenshot of the binding (mqtt)
![image](https://user-images.githubusercontent.com/16493960/74869990-426f3300-5359-11ea-805f-d8108a1af9ce.png)

## Installation
 - Version of Zigbee2Mqtt: 1.9.0
 - Version of Zigbee2MqttAssistant: 0.3.133
 - Installation type (HASS.IO, Docker...): HASS.IO
 - Docker version + CPU type (amd64, arm arm64...): HASS.IO latest, x86

## Pertinent logs
```
Starting Zigbee2MqttAssistant v0.3.133+Branch.master.Sha.f490bd70a0401bc6d96a4d02d5f9022a43bb5e9e...
Hosting environment: Production
Content root path: /app
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
fail: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Error processing MQTT message on topic 'zigbee2mqtt/bridge/bind/woonkamer_switch'
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: w. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at Zigbee2MqttAssistant.Services.BridgeStateService.UpdateDevice(String friendlyName, String jsonPayload, Boolean& forceLastSeen) in d:\a\1\s\Zigbee2MqttAssistant\Services\BridgeStateService.cs:line 79
   at Zigbee2MqttAssistant.Services.MqttConnectionService.DispatchZigbee2MqttMessage(MqttApplicationMessage msg) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 428
   at Zigbee2MqttAssistant.Services.MqttConnectionService.HandleApplicationMessageReceivedAsync(MqttApplicationMessageReceivedEventArgs eventArgs) in d:\a\1\s\Zigbee2MqttAssistant\Services\MqttConnectionService.cs:line 329
```

**Comment by magpern** [comment]
Do you not see `woonkamer_switch` and `woonkamer_sfeer` at all? 
I'm a little unsure how it should look.
There was a bug fixed today in `UpdateDevice` (from stack trace above), but that fix just validates the json before parsing. It will do nothing for this problem!

Please elaborate

**Comment by tabnul** [comment]
Hi, woonkamer_switch is visible, but it does not have a binding according to zigbee2mqttAssistant. Probably related to that error (parsing seems to fail on first character (w)
woonkamer_sfeer is a group, containing some lights.

As you see in the screenshot, there is actually a binding on mqtt level (and that binding is working and interpreted correctly by zigbee2mqtt). It is a binding between the switch, and the friendly name of the group, as described in
https://www.zigbee2mqtt.io/information/binding.html

**Comment by tabnul** [comment]
By the way last update indeed did not fix it.

**Comment by magpern** [comment]
@tabnul Yes I know. Latest fix has nothing to do with this, and should not have fixed this.

The command
`Zigbee2MqttAssistant.Services.BridgeStateService.UpdateDevice(String friendlyName, String jsonPayload, Boolean& forceLastSeen)`
updates the information about a device. It requires a JSON string with information about the device.
What you see with the binding is something else, I don't think it should reach the UpdateDevice at all.

I havn't been able to investigate further, my zigbee controller refuses to start after a reboot of the computer. It's a CC1352P-2 and there is some problem with it in zigbee2mqtt.

**Comment by tabnul** [comment]
not occurring anymolre
