### ISSUE TITLE
OTA update command

### ISSUE THREAD

**Issue by remb0** [yllibed/Zigbee2MqttAssistant#197]
**Is your feature request related to a problem? Please describe.**
feature request

**Describe the solution you'd like**
When an update is available it would be nice to click on a update update to send the update command.

**Additional context**
is also would be nice to see not only that an update is available but also which version. so we can check changelog of the device firmware update.

**Comment by CodeFinder2** [comment]
Duplicate of #184 ...

**Comment by carldebilly** [comment]
Have been implemented by @magpern in pr #184 
Definitely a duplicated.  Thanks for asking!
