### ISSUE TITLE
[BUG] Home Assistant menu bar missing in app

### ISSUE THREAD

**Issue by jcassee** [yllibed/Zigbee2MqttAssistant#200]
# Describe the bug

When using the Home Assistant Android app, the menu bar is missing on the Zigbee2Mqtt screens.

## To Reproduce

1. Open the Home Assistant Android app.
2. Click on the Zigbee2Mqtt menu item.
3. The top menu bar is gone.

**Expected behavior**

The Zigbee2Mqtt screen should have a top menu bar to navigate to other screens.

## Steps I took to try resolve the problem

The problem occurs with the latest release. Not sure how to try the latest development version with hass.io.

## Screenshots

Supervisor screen has top menu:

<img src="https://user-images.githubusercontent.com/20749/75614965-60e5e300-5b3e-11ea-8299-5d4982e57dff.jpg" width="200">

Zigbee2Mqtt screen does not have top menu:

<img src="https://user-images.githubusercontent.com/20749/75614978-912d8180-5b3e-11ea-960e-1ece02edcfde.jpg" width="200">

## Installation
 - Version of Zigbee2Mqtt: 1.11.0
 - Version of Zigbee2MqttAssistant: 0.3.133
 - Installation type (HASS.IO, Docker...): HASS.IO
 - Docker version + CPU type (amd64, arm arm64...): _Raspberry Pi 4_

## Pertinent logs

_n/a_

## Additional context

_none_

**Comment by magpern** [comment]
Are you sure?
The top menu for supervisor is part of the supervisor.
If I open visual code for instance, there is no top menu (only plugin I have atm besides Z2MA)

Do you have any other examples of add-ons that have a top menu?

**Comment by jcassee** [comment]
Ah, indeed. The only pages that have a top menu are the internal components. They can probably get the info to render it. It is a bit annoying in the app, though, so I'll see if I can find something about it in the Home Assistant repository.

Thanks!

**Comment by jcassee** [comment]
So the thing is this: Home Assistant will hide the navigation menu if the screen is narrow enough (i.e. on mobile). Internal screens will add the `ha-menu-button` in their top menu. But the navigation menu panel can also be dragged in from the left. Unfortunately, the new Android gestures use that for the "back button" functionality, so it's not very discoverable.

Anyway, your suggestion pointed me in the right direction. Thanks again.

**Comment by carldebilly** [comment]
@jcassee If you know any mean to navigate back to HA from an add-on...  I would be happy to add it to Z2MA :-).

**Comment by magpern** [comment]
@carldebilly I don't think one should be able to navigate back, because one never navigated away.

It is just home assistant that resizes and hides the left pane on smaller screens.
On a workstation the left pane is available the whole time.
On my phone you swipe and hold left to right to see the left pane again.

I think it is more a HA thing. Probably by design

**Comment by jcassee** [comment]
Indeed, the top menu is part of the page iframe. The internal pages all use the same framework, so it's easy for those to display a top menu in the correct style.

Anyway, @magpern is right. Unless there is some official way of doing this (and I have not found any indication of that) there is not much this project can/should do.
