### ISSUE TITLE
Support Rider development environment

### ISSUE THREAD

**Issue by magpern** [yllibed/Zigbee2MqttAssistant#202]
**Is your feature request related to a problem? Please describe.**
Z2MAssistant builds fine in Visual Studio 2019
Z2MA does not build at all using Rider from Intellij. One of the Uno dependencies just gives error 2 

**Describe the solution you'd like**
I guess the problem is really not Z2MA, but its dependancies
But supporting Rider, would enable development on Linux desktops (and MacOS (but it has visual studio))

https://www.jetbrains.com/rider/

**Comment by carldebilly** [comment]
I have a full licensed Rider... I should try it for Z2MA...  right now I'm using VS 2019.

**Comment by magpern** [comment]
I have opened a ticket at JetBrains

https://youtrack.jetbrains.com/issue/RIDER-41124

**Comment by magpern** [comment]
It is a InteliJ issue... and I don't know how to assist them.. so they closed the ticket

**Comment by carldebilly** [comment]
I know the solution : the problem is fixed in the latest version of UNO source gen...

**Comment by carldebilly** [comment]
Should work now.
