### ISSUE TITLE
Implement a badge for firmware update

### ISSUE THREAD

**Issue by magpern** [yllibed/Zigbee2MqttAssistant#206]
In the device overview there is no easy way to see if a device has a new firmware.
You have to click on each device to visually see if there is a new firmware.

Suggestion: Implement a badge on each device on the Devices page, to show if update is available.
Somewhere in the red box below

![image](https://user-images.githubusercontent.com/6589760/75761534-8985fc80-5d39-11ea-8f52-e802ffb1983f.png)

**Comment by magpern** [comment]
How about this?
Text ok? Color ok?

![image](https://user-images.githubusercontent.com/6589760/75830810-11a7e880-5db2-11ea-8f4c-6b3c689d3d24.png)

**Comment by CodeFinder2** [comment]
@magpern and @carldebilly what do you think about this?

https://github.com/Koenkk/zigbee2mqtt/issues/2921#issuecomment-594441372

**Comment by magpern** [comment]
@CodeFinder2 I got exactly the same thought yesterday. So, yes - I think it should be changed
