### ISSUE TITLE
Implement the friendly name

### ISSUE THREAD

**Issue by wes1993** [yllibed/Zigbee2MqttAssistant#207]
If is possible add and option or just the function tu see the friendly name instead of the zigbee2mqtt entity id in device list, with some check with homeassistant entity database.

Thanks a Lot
Stefano

**Comment by carldebilly** [comment]
I'm not sure I understand what you're asking. It's already displaying the _Z2M friendly name_.

**Comment by wes1993** [comment]
I don’t have put friendly name in Z2M but only in HA so for me the list of my devices is 0x0xxxxxxxxx but in homeassistant I have the friendly name.
If the software can take the friendly name from HA instead of Z2M

**Comment by magpern** [comment]
@wes1993 That is not possible. The Name Override in Home Assistant is just in home assistant. In the zigbee world it is still 0x0xxxxxxxx.
The overridden name is never broarcasted to MQTT, so Z2MA (or Z2M) will never pick it up.

What you will have to do is to change the friendly name in your zigbee network.
This friendly name from zigbee will be broadcasted to Home Assistant, and it will create entities with the name.

You can change in the zigbee2mqtt configfile
![image](https://user-images.githubusercontent.com/6589760/75864182-eb119e00-5e01-11ea-866e-1f89f8913886.png)
or in Z2MA
![image](https://user-images.githubusercontent.com/6589760/75864292-13999800-5e02-11ea-9f82-178e59dc4741.png)

then it will appear correct in Z2MA
![image](https://user-images.githubusercontent.com/6589760/75864462-55c2d980-5e02-11ea-8de0-9ffe718a11c8.png)

**Comment by wes1993** [comment]
Thanks a lot for your reply!!
I will do from Z2MA

**Comment by carldebilly** [comment]
@all-contributors please add magpern to question
Thanks @magpern with your previous help on this repo!
