### ISSUE TITLE
Implement a zigbee graph visualization

### ISSUE THREAD

**Issue by carldebilly** [yllibed/Zigbee2MqttAssistant#21]
Requested here: https://github.com/Koenkk/zigbee2mqtt/issues/1834#issuecomment-528342502

**Comment by carldebilly** [comment]
Idea: use "d3-force" to display graph: https://github.com/d3/d3-force

**Comment by neographikal** [comment]
I would very much like this!

**Comment by carldebilly** [comment]
I know... I want this for myself.  Anyway, all this project has been created for myself at first ;-)

**Comment by carldebilly** [comment]
Implemented!

**Comment by neographikal** [comment]
Really cool, will try!
