### ISSUE TITLE
[BUG] Unknown devices

### ISSUE THREAD

**Issue by SargonofAssyria** [yllibed/Zigbee2MqttAssistant#224]
# Describe the bug
Unknown devices show up when ever Zigbee2MqttAssistent is restarted.
A few (old) devices show up, which cannot be deleted, after every (re)start of Zigbee2MqttAssistant.
When I delete the device in the webui, I see messages in the zigbee2mqtt.log
`error 2020-03-08 17:31:11: Cannot remove, device 'Brievenbus' does not exist
info  2020-03-08 17:31:11: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"device_removed_failed","message":"Brievenbus"}'
`
So zigbee2mqtt does not know any of these devices.
How do I get rid of these devices?
I am running Zigbee2MqttAssistant in Docker on a Synology DS1517+

**Comment by magpern** [comment]
@SargonofAssyria I don't exactly know how to help you, but once thing is for sure. Zigbee2MQTTAssistant does not store any information about your network, none at all.
Everything is read from the MQTT Server, especially when Z2MA starts up.
It listens to the topics `zigbee2mqtt `(or what every you named your zigbee2mqtt topic) and it listens to the `homeassistant`
It gets all its information from there. Run `MQTT Explorer` from a workstation and look in these topics and see if you see your `Brievenbus` device anywhere, In `MQTT Explorer` you can search for it.

You can also take it one step further and check the file `configuration.yaml` in the zigbe2mqtt application.

I'm pretty sure it is not a bug in Z2MA itself, more of a `something-is-out-of-sync` problem.

I assume you have rebooted the MQTT server, to clear up all not retained entries.

**Comment by SargonofAssyria** [comment]
Tnx, for the carification. It was a retained message.
