### ISSUE TITLE
Remote Zigbee2MqttAssistant docker to Raspberry Pi Zigbee2Mqtt

### ISSUE THREAD

**Issue by nahk-eeza** [yllibed/Zigbee2MqttAssistant#235]
Hi,
i am not sure if its a bug or a request for a new features.
i installed the Zigbee2Mqtt on Raspberry Pi 3B+ with CC2531 , and this is working fine.
now my problem is i installed the Zigbee2MqttAssistant on a docker but on a different host (i have a VM where i install my few other containers).
so is it possible to map the Zigbee2MqttAssistant to a Raspberry Pi Zigbee2MqttAssistant?

the aim is to be less dependent on the Raspberry Pi SD card.

**Comment by magpern** [comment]
@nahk-eeza not really following what you want to do.
But, you can install zigbee2mqttAssistant wherever you want, as long as that computer that runs the Z2MA can reach the MQTT server.
I even have two installations of Z2MA omn two different computers, both reading the same MQTT. Works fine so far.

**Comment by nahk-eeza** [comment]
Thanks, as i am new to mqtt and zigbee, my assumption was zigbee2mqttAssistant must point to zigbee2mqtt.
now i understand zigbee2mqttAssistant must point to MQTT.
i change the zigbee2mqttAssistant settings and point to my mqtt, it works now :)
