### ISSUE TITLE
[BUG]  Doing a /get on a device makes a new device appear in z2m assistant interface

### ISSUE THREAD

**Issue by Botched1** [yllibed/Zigbee2MqttAssistant#239]
# Describe the bug
Doing a /get command on a device makes a new device appear in z2m assistant interface

## To Reproduce
Do a "zigbee2mqtt/[FRIENDLY_NAME]/get" on a device. Description from the z2m docs below: 
zigbee2mqtt/[FRIENDLY_NAME]/get #
This is the counterpart of the set command. It allows you to read a value from a device. To read e.g. the state of a device send the payload:

{
  "state": ""
}

**Expected behavior**
No new device should appear in z2m assistant, as there is no new device.

Example of interface after doing "zigbee2mqtt/Storage Room Door/get":
![image](https://user-images.githubusercontent.com/19985320/77962512-5899d880-72a1-11ea-8a54-9399fb44f98f.png)

**Comment by magpern** [comment]
Just so you all know, the last week there has been like 7 new bugs/issues/requests. I/we (@carldebilly) are not ignoring them, it is just a fact that the SARS-Covid-19 virus is causing some problems focusing on this project. Day-job is in quarantine, meaning normal work hours vary, and available extra hours are limited.
I/we will get back on this when things settle down.

**Comment by Botched1** [comment]
> Just so you all know, the last week there has been like 7 new bugs/issues/requests. I/we (@carldebilly) are not ignoring them, it is just a fact that the SARS-Covid-19 virus is causing some problems focusing on this project. Day-job is in quarantine, meaning normal work hours vary, and available extra hours are limited.
> I/we will get back on this when things settle down.

No hurry! I just wanted to get this one "in the queue", so to speak.

Take care!

**Comment by diveflo** [comment]
This looks like #176 if I‘m not mistaken

**Comment by Botched1** [comment]
> This looks like #176 if I‘m not mistaken

Oops, you are correct. I'll close this one.
