### ISSUE TITLE
[BUG] Devices removed from z2m still show up on z2ma web interface

### ISSUE THREAD

**Issue by Botched1** [yllibed/Zigbee2MqttAssistant#243]
I have a number of devices I removed from z2m. I have verified that they no longer exist in database.db and do not exist in configuration.yaml. I also do not see the devices in MQTT.

However, even after resetting state in z2ma the devices still show up in the list.

Where is it getting that info from, and how do I get rid of these no longer existing devices in the interface?

**Comment by magpern** [comment]
Z2MA gets most of it's device data from the `homeassistant` mqtt topic. Check this and see if you find the devices there.

**Comment by Botched1** [comment]
> Z2MA gets most of it's device data from the `homeassistant` mqtt topic. Check this and see if you find the devices there.

I didn't realize that! Yes, they were still in there. Removing that fixed it. Thank you!
