### ISSUE TITLE
[BUG] Network Map not showing any connections

### ISSUE THREAD

**Issue by aund** [yllibed/Zigbee2MqttAssistant#252]
# Describe the bug

While working previously, clicking on map shows my devices but no connections between them. There is also a message that says "MAP NOT AVAILABLE YET - REFRESH TO SEE SOMETHING.". When I click refresh, it just shows me the same thing.

**Expected behavior**
The map showing connections between devices.

## Steps I took to try resolve the problem
Removed add on, reinstalled. Also tried removing all devices from mqtt and adding back in, which fixed temporarily. 

## Installation
 - Version of Zigbee2Mqtt: 1.12.0
 - Version of Zigbee2MqttAssistant: 0.3.147 
 - Installation type (HASS.IO, Docker...): Hass.io
 - Docker version + CPU type (amd64, arm arm64...): 

## Additional context
I'm also very occasionally seeing other stability issues with zigbee2mqtt (occasionally devices are slow to respond or I see intermittent errors in the zigbee2mqtt logs).

**Comment by aund** [comment]
Closing as this looks to be zigbee2mqtt related.

**Comment by mf-1** [comment]
Same here ... also using amd64 (raspi os 64bit)
Using Docker for Z2A
