### ISSUE TITLE
BridgeStateService: Unable to find friendly name from topic

### ISSUE THREAD

**Issue by heubi76** [yllibed/Zigbee2MqttAssistant#26]
Running clean Hass.io install with zigbee2mqtt all up and running as it should.
MQTT Server is extern (loxberry). Get the following fault when I start the Assistant?

Log
warn: Zigbee2MqttAssistant.Services.BridgeStateService[0] Unable to find friendly name from topic mqtt/kontakt10 in entity 0x00158d00022b3819-sensor-linkquality.

**Comment by carldebilly** [comment]
That's just a warning in the output.  Is it causing a functional problem?

**Comment by heubi76** [comment]
Unfortunatelly yes...no Sensor is in the list of devices on the webui...
I filled in just the ip without port in the server field..
If I fill out the ip with the port it wont find the server?

**Comment by carldebilly** [comment]
For the port it's another setting. Check this:
https://github.com/yllibed/Zigbee2MqttAssistant#settings

**Comment by carldebilly** [comment]
Fixed in latest version `0.2.0-dev.94`!

Please test it and come back if there's any problem remaining.

**Comment by carldebilly** [comment]
@all-contributors please add heubi76 to bugs
