### ISSUE TITLE
Container fails with starting[BUG]

### ISSUE THREAD

**Issue by nexro567** [yllibed/Zigbee2MqttAssistant#262]
# Describe the bug
Containers fails with starting after adding new devices. I can not fix it anymore.

## To Reproduce

**Expected behavior**

## Steps I took to try resolve the problem
Open a new container in docker. Still same problem. 
I added in config
`advanced:
  pan_id: 0x1a63`

No fix, after that I reset local state, still no change :(

## Pertinent logs
sing '/app/data' as data directory
Creating configuration file...

> zigbee2mqtt@1.13.0 start /app
> node index.js

[32mzigbee2mqtt:info [39m 2020-05-01 22:33:26: Logging to console and directory: '/app/data/log/2020-05-01.22-33-26' filename: log.txt
[32mzigbee2mqtt:info [39m 2020-05-01 22:33:26: Starting zigbee2mqtt version 1.13.0 (commit #55e6283)
[32mzigbee2mqtt:info [39m 2020-05-01 22:33:26: Starting zigbee-herdsman...
[32mzigbee2mqtt:info [39m 2020-05-01 22:33:28: zigbee-herdsman started
[32mzigbee2mqtt:info [39m 2020-05-01 22:33:28: Coordinator firmware version: '{"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}}'
[32mzigbee2mqtt:info [39m 2020-05-01 22:33:28: Currently 0 devices are joined:
[33mzigbee2mqtt:warn [39m 2020-05-01 22:33:28: `permit_join` set to  `true` in configuration.yaml.
[33mzigbee2mqtt:warn [39m 2020-05-01 22:33:28: Allowing new devices to join.
[33mzigbee2mqtt:warn [39m 2020-05-01 22:33:28: Set `permit_join` to `false` once you joined all devices.
[32mzigbee2mqtt:info [39m 2020-05-01 22:33:28: Zigbee: allowing new devices to join.
[32mzigbee2mqtt:info [39m 2020-05-01 22:33:28: Connecting to MQTT server at mqtt://localhost
[32mzigbee2mqtt:info [39m 2020-05-01 22:33:28: Connected to MQTT server
[32mzigbee2mqtt:info [39m 2020-05-01 22:33:28: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
[32mzigbee2mqtt:info [39m 2020-05-01 22:33:28: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"version":"1.13.0","commit":"55e6283","coordinator":{"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}},"log_level":"info","permit_join":true}'
[32mzigbee2mqtt:info [39m 2020-05-01 22:33:33: MQTT publish: topic 'zigbee2mqtt/bridge/config/devices', payload '[{"ieeeAddr":"0x00124b00193e51cc","type":"Coordinator","networkAddress":0,"friendly_name":"Coordinator","softwareBuildID":"zStack12","dateCode":"20190608","lastSeen":1588372413635}]'
[32mzigbee2mqtt:info [39m 2020-05-01 22:33:33: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"devices","message":[{"ieeeAddr":"0x00124b00193e51cc","type":"Coordinator","networkAddress":0,"friendly_name":"Coordinator","softwareBuildID":"zStack12","dateCode":"20190608","lastSeen":1588372413637}]}'
[32mzigbee2mqtt:info [39m 2020-05-01 22:33:50: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'offline'
[32mzigbee2mqtt:info [39m 2020-05-01 22:33:50: Disconnecting from MQTT server
[32mzigbee2mqtt:info [39m 2020-05-01 22:33:50: zigbee-herdsman stopped
Using '/app/data' as data directory

> zigbee2mqtt@1.13.0 start /app
> node index.js

[32mzigbee2mqtt:info [39m 2020-05-01 22:34:19: Logging to console and directory: '/app/data/log/2020-05-01.22-34-19' filename: log.txt
[32mzigbee2mqtt:info [39m 2020-05-01 22:34:19: Starting zigbee2mqtt version 1.13.0 (commit #55e6283)
[32mzigbee2mqtt:info [39m 2020-05-01 22:34:19: Starting zigbee-herdsman...
[32mzigbee2mqtt:info [39m 2020-05-01 22:34:20: zigbee-herdsman started
[32mzigbee2mqtt:info [39m 2020-05-01 22:34:20: Coordinator firmware version: '{"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}}'
[32mzigbee2mqtt:info [39m 2020-05-01 22:34:20: Currently 0 devices are joined:
[33mzigbee2mqtt:warn [39m 2020-05-01 22:34:20: `permit_join` set to  `true` in configuration.yaml.
[33mzigbee2mqtt:warn [39m 2020-05-01 22:34:20: Allowing new devices to join.
[33mzigbee2mqtt:warn [39m 2020-05-01 22:34:20: Set `permit_join` to `false` once you joined all devices.
[32mzigbee2mqtt:info [39m 2020-05-01 22:34:20: Zigbee: allowing new devices to join.
[32mzigbee2mqtt:info [39m 2020-05-01 22:34:21: Connecting to MQTT server at mqtt://localhost
[32mzigbee2mqtt:info [39m 2020-05-01 22:34:21: Connected to MQTT server
[32mzigbee2mqtt:info [39m 2020-05-01 22:34:21: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'online'
[32mzigbee2mqtt:info [39m 2020-05-01 22:34:21: MQTT publish: topic 'zigbee2mqtt/bridge/config', payload '{"version":"1.13.0","commit":"55e6283","coordinator":{"type":"zStack12","meta":{"transportrev":2,"product":0,"majorrel":2,"minorrel":6,"maintrel":3,"revision":20190608}},"log_level":"info","permit_join":true}'
[32mzigbee2mqtt:info [39m 2020-05-01 22:34:21: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"entity_not_found","message":{"friendly_name":"0xccccccfffeb3c6a7"}}'
[31mzigbee2mqtt:error[39m 2020-05-01 22:34:21: Entity '0xccccccfffeb3c6a7' is unknown
[32mzigbee2mqtt:info [39m 2020-05-01 22:34:26: MQTT publish: topic 'zigbee2mqtt/bridge/config/devices', payload '[{"ieeeAddr":"0x00124b00193e51cc","type":"Coordinator","networkAddress":0,"friendly_name":"Coordinator","softwareBuildID":"zStack12","dateCode":"20190608","lastSeen":1588372466148}]'
[32mzigbee2mqtt:info [39m 2020-05-01 22:34:26: MQTT publish: topic 'zigbee2mqtt/bridge/log', payload '{"type":"devices","message":[{"ieeeAddr":"0x00124b00193e51cc","type":"Coordinator","networkAddress":0,"friendly_name":"Coordinator","softwareBuildID":"zStack12","dateCode":"20190608","lastSeen":1588372466159}]}'
[32mzigbee2mqtt:info [39m 2020-05-01 22:34:51: Starting network scan (includeRoutes 'false')
[31mzigbee2mqtt:error[39m 2020-05-01 22:34:51: Adapter disconnected, stopping
[32mzigbee2mqtt:info [39m 2020-05-01 22:34:51: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload 'offline'
[32mzigbee2mqtt:info [39m 2020-05-01 22:34:51: Disconnecting from MQTT server
[31mzigbee2mqtt:error[39m 2020-05-01 22:34:51: Failed to stop zigbee
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.13.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the zigbee2mqtt@1.13.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-01T22_34_51_639Z-debug.log
Using '/app/data' as data directory

**Comment by magpern** [comment]
I think you have made a bug in the wrong github repository. The bug you describe is zigbee2mqtt, this is the zigbee2mqttAssistant

Head over to zigbee2mqtt https://github.com/Koenkk/zigbee2mqtt

**Comment by nexro567** [comment]
Thanks magpern!
