### ISSUE TITLE
[BUG] Device is twice on the list of devices

### ISSUE THREAD

**Issue by panec** [yllibed/Zigbee2MqttAssistant#269]
# Describe the bug
The same device is twice on the list of devices

## To Reproduce
Don't know. It might be connected with renaming of the devide

**Expected behavior**
Device is only once on the list

## Steps I took to try resolve the problem
I tried resetting the settings via: "Reset Zigbee2Mqtt Assistant" and removing the device via delete option with and without force option but received errors in log.

## Screenshots
![image](https://user-images.githubusercontent.com/2536779/81506654-d06f1000-92ef-11ea-81b4-9fd9ed980058.png)

## Installation
- Version of Zigbee2MqttAssistant (this software): 0.3.147 
- Version of Zigbee2Mqtt: 1.13.0
- HASS.IO
- Raspberry Pi4

## Pertinent logs
```
{"ieeeAddr":"0x00158d000408d137","type":"EndDevice","networkAddress":48553,"model":"WSDCGQ01LM","vendor":"Xiaomi","description":"MiJia` temperature & humidity sensor","friendly_name":"Xiaomi Sensor 4","manufacturerID":4151,"manufacturerName":"LUMI","powerSource":"Battery","modelID":"lumi.sensor_ht","lastSeen":1589132728506}]}
```

**Comment by panec** [comment]
This is not a common knowledge (no mentioning in readme) but the info about devices is served from MQTT so to fix my issue I used MQTT Explorer http://mqtt-explorer.com/ to delete problematic entry.

**Comment by carldebilly** [comment]
@all-contributors please add panec to question
