### ISSUE TITLE
[BUG] Device is unresponsive

### ISSUE THREAD

**Issue by to4ko** [yllibed/Zigbee2MqttAssistant#275]
# Describe the bug

Device marked as UNRESPOSIVE  while it's fully operational in Home assistant 
## To Reproduce
not sure how to reproduce

**Expected behavior**

Correct device marking in list and on the network map

## Steps I took to try resolve the problem

latest stable used
## Screenshots

Aqara Motion Sensor
![image](https://user-images.githubusercontent.com/45161980/82023059-55fb1300-9696-11ea-8fa0-6ca8a592107f.png)

Mi Plug
![image](https://user-images.githubusercontent.com/45161980/82023103-67441f80-9696-11ea-826b-804a76a1f761.png)

## Installation
 - Version of Zigbee2Mqtt: 1.13
 - Version of Zigbee2MqttAssistant: 0.3.147
 - Installation type (HASS.IO, Docker...): HA Core Supervised
 - Docker version + CPU type (amd64, arm arm64...): Docker 19.03.8, CPU Celeron j3455 and Xeon 2620v3

**Comment by carldebilly** [comment]
The device is marked as unresponsive because of the date/time of the last known communication, as reported by Zigbee2Mqtt.

**Comment by to4ko** [comment]
> The device is marked as unresponsive because of the date/time of the last known communication, as reported by Zigbee2Mqtt.

shouldn't time\date be updated when there was an interaction with device? i was switching the plug and pressing the button on motion senor with no success

z2m assistant add on restart helped - i'ts now showing correct status
