### ISSUE TITLE
Unable to qualify a message received on topic 'zigbee2mqtt/bridge/config/groups'.

### ISSUE THREAD

**Issue by remb0** [yllibed/Zigbee2MqttAssistant#28]
when starting everything looks fine, but alle my devices are "offline". when checking the logs of 
Zigbee2MqttAssistant I only see:

Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to qualify a message received on topic 'zigbee2mqtt/bridge/config/groups'.

Do I miss something?

**Comment by remb0** [comment]
Every device is: This device is considered as OFFLINE by Zigbee2Mqtt.
but bridge is online and devices seems to work.

**Comment by carldebilly** [comment]
Both those messages are not important.  I mean:
1. For the warning in the output, it's just a message to warn it received a message it can't process. There's no impact for this.
2. For the `OFFLINE` thing, that's known to be unreliable by _Zigbee2Mqtt_:
    https://github.com/yllibed/Zigbee2MqttAssistant/issues/15
    https://github.com/Koenkk/zigbee2mqtt/issues/1598
    https://github.com/Koenkk/zigbee-herdsman/issues/13
