### ISSUE TITLE
[BUG] Wrong Linkquality in GUI vs MQTT data

### ISSUE THREAD

**Issue by to4ko** [yllibed/Zigbee2MqttAssistant#283]
# Describe the bug

Wrong link quality displayed for number of devices and device type (no-neutral switch marked as Router)

![image](https://user-images.githubusercontent.com/45161980/83497317-f5a40800-a4c2-11ea-91a6-76997f89d9d0.png)

same time in MQTT
![image](https://user-images.githubusercontent.com/45161980/83497422-22f0b600-a4c3-11ea-916b-6030a649bffa.png)

**Expected behavior**

correct lqi and device type

## Steps I took to try resolve the problem

addons restart

## Installation
 - Version of Zigbee2Mqtt: 1.13.1
 - Version of Zigbee2MqttAssistant: 0.3.157
 - Installation type (HASS.IO, Docker...): HA Core Supervised
 - Docker version + CPU type (amd64, arm arm64...): 19.03.8 amd64

**Comment by kennymc-c** [comment]
I also noticed this in the stand-alone version today when I repaired all my devices to a new zzh! CC2652R corridinator. In my case the value is not unknown but it does not match the value in the mqtt message. Apparently, Z2MA shows it also in another scale up to 255 and not up to 100.

**Comment by carldebilly** [comment]
That value is coming from the network graph request.  Maybe it should be smarter and use the value coming for the devices list also.
