### ISSUE TITLE
Removing devices does not remove entries in database.db 

### ISSUE THREAD

**Issue by BigCabbage** [yllibed/Zigbee2MqttAssistant#29]
First off, thanks for this GUI! It's working great and as expected.

However, when using the 'Remove' button to remove 'left-over' devices which are not present anymore, I can see the entries get removed from devices.yaml, but they are still present in database.db.
After restarting zigbee2mqtt, they reappear just without name.

Is this something you can fix, or something that needs to be fixed by KKoen?

I'm using Zigbee2mqtt addon for HASS.IO 1.6.0 and your latest Zigbee2MqttAssistant addon (0.2.0-dev.66)

**Comment by carldebilly** [comment]
It's definitetly in the @Koenkk's project.

I think we shouldn't use Z2MA to patch for this kind of bug.

**Comment by Koenkk** [comment]
@BigCabbage can you check if it still occurs in combination with zigbee2mqtt edge version?

**Comment by carldebilly** [comment]
I'll close this bug since it's not related to this project.  Please check issues in this project: https://github.com/Koenkk/zigbee2mqtt
