### ISSUE TITLE
[BUG] Error message: "driver failed programming external connectivity on endpoint addon_812b11b5_zigbee2mqttassistant ??? 

### ISSUE THREAD

**Issue by tedum11** [yllibed/Zigbee2MqttAssistant#294]
# Describe the bug

 I can see the the map for connection of my Zigbee sensor and Coordinator. But I got the error message like below when i clicked all any function such as "Allow join" or "Launch new network scan" and so on.

1) 20-06-30 02:06:46 ERROR (SyncWorker_13) [supervisor.docker] Can't start addon_812b11b5_zigbee2mqttassistant: 500 Server Error: Internal Server Error ("driver failed programming external connectivity on endpoint addon_812b11b5_zigbee2mqttassistant (e8aab1ee4f4e4fc8aa6be7a9d8d11111da6d678a6c6bf0b8aa2547e66): Bind for 0.0.0.0:80 failed: port is already allocated")

## To Reproduce
Whenever i click any menu such as "Allow join" or "Launch new network scan" and so on.

**Expected behavior**

## Steps I took to try resolve the problem
I didn't the Dev version yet. 

## Screenshots
when i click any button, I got the error message in the screen for Z2Ma like below. 

https://xx.xxxx.xxxx.org/api/hassio_ingress/Z_ZHL0NBUmZYi6g4YVCkzpFk9qsoUDiXfCNWHHY6x-E/Home/Scan <- this site might be temporary jammed or this might be moved to the completely new address. 
.

## Installation
 - Version of Zigbee2Mqtt: 1.14.0
 - Version of Zigbee2MqttAssistant: 0.3.157
 - Installation type (HASS.IO, Docker...): Hassio
 - Docker version + CPU type (amd64, arm arm64...):  RasberryPi 3

## Pertinent logs
1) 20-06-30 02:06:46 ERROR (SyncWorker_13) [supervisor.docker] Can't start addon_812b11b5_zigbee2mqttassistant: 500 Server Error: Internal Server Error ("driver failed programming external connectivity on endpoint addon_812b11b5_zigbee2mqttassistant (e8aab1ee4f4e4fc8aa6be7a9d8d11111da6d678a6c6bf0b8aa2547e66): Bind for 0.0.0.0:80 failed: port is already allocated")

## Additional context
As i am not a expert for this area, Can you please let me know what the error message means and how can i treat? 

Thank you very much.

**Comment by tedum11** [comment]
available

**Comment by EthicalCha0s** [comment]
Did you ever manage to fix this problem?
