### ISSUE TITLE
Move JS/CSS Locally or Fallback to local files

### ISSUE THREAD

**Issue by brendanmullan** [yllibed/Zigbee2MqttAssistant#30]
Hey,

Just a suggestion but when the internet is down the Zigbee2MqttAssistant page within hass.io has broken styling due to the fact it calls Google Fonts / jQuery / Bootstrap etc from remote sources. 

If for some reason you really want to keep the remote sources, you could always implement a [fallback](https://builtvisible.com/setting-local-fallback-jquery-served-via-cdn/) to local files.

Thanks for all the excellent work!

**Comment by carldebilly** [comment]
dotnet core is supposed to do that automatically... but I never tested it. Let me flag this as a feature in the backlog.

**Comment by carldebilly** [comment]
Have been done in last version.  So it's done!

**Comment by carldebilly** [comment]
@all-contributors please add brendanmullan to ideas

**Comment by brendanmullan** [comment]
Awesome thanks for the fix @carldebilly 😁

**Comment by carldebilly** [comment]
Is it working correctly?

**Comment by brendanmullan** [comment]
Seems to be working fine now 👍
