### ISSUE TITLE
Rock64 Support

### ISSUE THREAD

**Issue by chrisrock1984** [yllibed/Zigbee2MqttAssistant#304]
I am running Hassio on an Ubuntu System on a Rock64 Board. Would it be possible to also make it available there?
Otherwise I need to move to a Raspberry Pi 

Thank you!!

**Comment by carldebilly** [comment]
Rock64 is using a [Cortex A53 CPU](https://store.pine64.org/product/rock64-media-board-computer/), which is [implementing the ARM v8-A instructions set](https://en.wikipedia.org/wiki/Comparison_of_ARMv8-A_cores).

That means it should work directly on those boards, unchanged. Please specify which kind of problem you're experiencing.

(thanks for the reference of that board... seems very nice, didn't know it!)

**Comment by XRyu** [comment]
@chrisrock1984 have a look at the docker examples, should work with this easily out of the box :)

**Comment by chrisrock1984** [comment]
That is my Host Sytem ->
![image](https://user-images.githubusercontent.com/22988621/87971118-1fda7500-cac5-11ea-86d9-18eabac929d6.png)

That is the issue i have ->
![image](https://user-images.githubusercontent.com/22988621/87971205-3ed90700-cac5-11ea-9584-562f93bd23e3.png)
![image](https://user-images.githubusercontent.com/22988621/87971248-4f897d00-cac5-11ea-97e8-b3d89d9007a0.png)

**Comment by chrisrock1984** [comment]
> Rock64 is using a [Cortex A53 CPU](https://store.pine64.org/product/rock64-media-board-computer/), which is [implementing the ARM v8-A instructions set](https://en.wikipedia.org/wiki/Comparison_of_ARMv8-A_cores).
> 
> That means it should work directly on those boards, unchanged. Please specify which kind of problem you're experiencing.
> 
> (thanks for the reference of that board... seems very nice, didn't know it!)

This board is great! I have the 4GB version and running Hassio for more than 2 years on a SSD. But I am planning to move to Pi4 as this great tool is not running on the rock64 so far. At least I am not able to get it running ;-)

**Comment by chrisrock1984** [comment]
I was able to install it with the direct docker installation - simply WOW!! What a great tool!!
