### ISSUE TITLE
[BUG] Panel Icon deprecated

### ISSUE THREAD

**Issue by dreimer1986** [yllibed/Zigbee2MqttAssistant#306]
# Describe the bug

Installing 0.113.B3 starts to throw this error message: "Icon mdi:mixcloud was removed from MDI, please replace this icon with an other icon in your config, it will be removed in version 0.115."
The message comes from this addon.

## To Reproduce

Just update to 0.113.X and look into the logs.

**Expected behavior**

New icon needs to be chosen before 0.115 wipes the icon.

## Installation
 - Version of Zigbee2Mqtt: 0.113.B3
 - Version of Zigbee2MqttAssistant: 0.3.175+Branch.master.Sha.f1dc298d292590e077def97c9aa0cd4924dfbb11
 - Installation type (HASS.IO, Docker...): HASSIO
 - Docker version + CPU type (amd64, arm arm64...): AMD64

## Pertinent logs

"Icon mdi:mixcloud was removed from MDI, please replace this icon with an other icon in your config, it will be removed in version 0.115."

**Comment by carldebilly** [comment]
@dreimer1986 Which icon do you propose?  Feel free to make a PR if you wish :-)

**Comment by dreimer1986** [comment]
OMG, my second try ever to make a pull request. https://github.com/yllibed/hassio/pull/4 Hopefully correctly done... ^^

**Comment by mDieli** [comment]
I'm not very fond on the mdi:zigbee icon to be honest. Maybee is it possible to make it changeable through the Configuration/settings? This way everyone can use his/hers own icon. :)

**Comment by SamuelCarson** [comment]
Follow

**Comment by nanobra1n** [comment]
`mdi:graphql` looks like a mesh map, or if you like a pun `mdi:bee`.

**Comment by bwestrek** [comment]
If I would choose then it will be the mdi:graphql. Think it fits best.

**Comment by mDieli** [comment]
Not to be disrespectful or anything, but I don't understand why it needs to take more than 2 months to change the icon to something different ?

**Comment by bwestrek** [comment]
Any idea when it will be solved. Indeed, it takes a very long time. Since it has been indicated a long time ago the MDI icons have changed.
