### ISSUE TITLE
No Devices are shown in the list / map[BUG]

### ISSUE THREAD

**Issue by W3azl3** [yllibed/Zigbee2MqttAssistant#310]
# Describe the bug
I'm using openhab moquette, zigbee2mqtt and zigbee2mqttassistant, everything running via docker, started via docker-compose using nowhere passwords (because it is just in my local network available). 
There are no devices shown in the "Devices"-Tab. In the Map it is the same. Maybe this is an Authentication Problem?

In general the connection looks like it is working, because in the MQTT.fx I can see the list of devices when i allow the join. 

### Log of MQTTfx

`
{
  "nodes" : [ {
    "ieeeAddr" : "0x0000000000000000",
    "friendlyName" : "Coordinator",
    "type" : "Coordinator",
    "networkAddress" : 0,
    "failed" : [ ],
    "lastSeen" : 1596395606446
  }, {
    "ieeeAddr" : "0x0000000000000000",
    "friendlyName" : "0x0000000000000000",
    "type" : "EndDevice",
    "networkAddress" : 20221,
    "manufacturerName" : "IKEA of Sweden",
    "modelID" : "TRADFRI open/close remote",
    "lastSeen" : 1596394456905
  }, {
    "ieeeAddr" : "0x0000000000000000",
    "friendlyName" : "0x0000000000000000",
    "type" : "Router",
    "networkAddress" : 52633,
    "manufacturerName" : "IKEA of Sweden",
    "modelID" : "TRADFRI bulb E14 WS opal 400lm",
    "failed" : [ ],
    "lastSeen" : 1596394476026
  }, {
    "ieeeAddr" : "0x0000000000000000",
    "friendlyName" : "0x0000000000000000",
    "type" : "Router",
    "networkAddress" : 59426,
    "manufacturerName" : "Philips",
    "modelID" : "LST002",
    "failed" : [ ],
    "lastSeen" : 1596390237425
  }, {
    "ieeeAddr" : "0x0000000000000000",
    "friendlyName" : "0x0000000000000000",
    "type" : "EndDevice",
    "networkAddress" : 15380,
    "manufacturerName" : "IKEA of Sweden",
    "modelID" : "KADRILJ roller blind",
    "lastSeen" : 1596394583930
  }, {
    "ieeeAddr" : "0x0000000000000000",
    "friendlyName" : "0x0000000000000000",
    "type" : "EndDevice",
    "networkAddress" : 23651,
    "manufacturerName" : "IKEA of Sweden",
    "modelID" : "TRADFRI open/close remote",
    "lastSeen" : 1596395328372
  }, {
    "ieeeAddr" : "0x0000000000000000",
    "friendlyName" : "0x0000000000000000",
    "type" : "EndDevice",
    "networkAddress" : 6427,
    "manufacturerName" : "IKEA of Sweden",
    "modelID" : "FYRTUR block-out roller blind",
    "lastSeen" : 1596399939528
  } ],
  "links" : [ {
    "source" : {
      "ieeeAddr" : "0x0000000000000000",
      "networkAddress" : 52633
    },
    "target" : {
      "ieeeAddr" : "0x0000000000000000",
      "networkAddress" : 0
    },
    "linkquality" : 19,
    "depth" : 1,
    "routes" : [ ],
    "sourceIeeeAddr" : "0x0000000000000000",
    "targetIeeeAddr" : "0x0000000000000000",
    "sourceNwkAddr" : 52633,
    "lqi" : 19,
    "relationship" : 1
  }, {
    "source" : {
      "ieeeAddr" : "0x0000000000000000",
      "networkAddress" : 59426
    },
    "target" : {
      "ieeeAddr" : "0x0000000000000000",
      "networkAddress" : 0
    },
    "linkquality" : 60,
    "depth" : 1,
    "routes" : [ ],
    "sourceIeeeAddr" : "0x0000000000000000",
    "targetIeeeAddr" : "0x0000000000000000",
    "sourceNwkAddr" : 59426,
    "lqi" : 60,
    "relationship" : 1
  }, {
    "source" : {
      "ieeeAddr" : "0x0000000000000000",
      "networkAddress" : 20221
    },
    "target" : {
      "ieeeAddr" : "0x0000000000000000",
      "networkAddress" : 0
    },
    "linkquality" : 82,
    "depth" : 1,
    "routes" : [ ],
    "sourceIeeeAddr" : "0x0000000000000000",
    "targetIeeeAddr" : "0x0000000000000000",
    "sourceNwkAddr" : 20221,
    "lqi" : 82,
    "relationship" : 1
  }, {
    "source" : {
      "ieeeAddr" : "0x0000000000000000",
      "networkAddress" : 15380
    },
    "target" : {
      "ieeeAddr" : "0x0000000000000000",
      "networkAddress" : 0
    },
    "linkquality" : 64,
    "depth" : 1,
    "routes" : [ ],
    "sourceIeeeAddr" : "0x0000000000000000",
    "targetIeeeAddr" : "0x0000000000000000",
    "sourceNwkAddr" : 15380,
    "lqi" : 64,
    "relationship" : 1
  }, {
    "source" : {
      "ieeeAddr" : "0x0000000000000000",
      "networkAddress" : 23651
    },
    "target" : {
      "ieeeAddr" : "0x0000000000000000",
      "networkAddress" : 0
    },
    "linkquality" : 84,
    "depth" : 1,
    "routes" : [ ],
    "sourceIeeeAddr" : "0x0000000000000000",
    "targetIeeeAddr" : "0x0000000000000000",
    "sourceNwkAddr" : 23651,
    "lqi" : 84,
    "relationship" : 1
  }, {
    "source" : {
      "ieeeAddr" : "0x0000000000000000",
      "networkAddress" : 59426
    },
    "target" : {
      "ieeeAddr" : "0x0000000000000000",
      "networkAddress" : 52633
    },
    "linkquality" : 155,
    "depth" : 15,
    "routes" : [ ],
    "sourceIeeeAddr" : "0x0000000000000000",
    "targetIeeeAddr" : "0x0000000000000000",
    "sourceNwkAddr" : 59426,
    "lqi" : 155,
    "relationship" : 2
  }, {
    "source" : {
      "ieeeAddr" : "0x0000000000000000",
      "networkAddress" : 0
    },
    "target" : {
      "ieeeAddr" : "0x0000000000000000",
      "networkAddress" : 59426
    },
    "linkquality" : 246,
    "depth" : 0,
    "routes" : [ ],
    "sourceIeeeAddr" : "0x0000000000000000",
    "targetIeeeAddr" : "0x0000000000000000",
    "sourceNwkAddr" : 0,
    "lqi" : 246,
    "relationship" : 0
  }, {
    "source" : {
      "ieeeAddr" : "0x0000000000000000",
      "networkAddress" : 52633
    },
    "target" : {
      "ieeeAddr" : "0x0000000000000000",
      "networkAddress" : 59426
    },
    "linkquality" : 252,
    "depth" : 1,
    "routes" : [ ],
    "sourceIeeeAddr" : "0x0000000000000000",
    "targetIeeeAddr" : "0x0000000000000000",
    "sourceNwkAddr" : 52633,
    "lqi" : 252,
    "relationship" : 3
  }, {
    "source" : {
      "ieeeAddr" : "0x0000000000000000",
      "networkAddress" : 6427
    },
    "target" : {
      "ieeeAddr" : "0x0000000000000000",
      "networkAddress" : 59426
    },
    "linkquality" : 252,
    "depth" : 2,
    "routes" : [ ],
    "sourceIeeeAddr" : "0x0000000000000000",
    "targetIeeeAddr" : "0x0000000000000000",
    "sourceNwkAddr" : 6427,
    "lqi" : 252,
    "relationship" : 1
  } ]
}
`

### Docker log of Zigbee2MqttAssistant

`Starting Zigbee2MqttAssistant v0.3.176+Branch.master.Sha.e8012650c0c78855c83668cb5cd52bdd281f6ed6...
warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {2b803fcf-61bb-49d0-9fa5-4d1cb216061f} may be persisted to storage in unencrypted form.
Hosting environment: Production
Content root path: /app
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
fail: Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery[7]
      An exception was thrown while deserializing the token.
Microsoft.AspNetCore.Antiforgery.AntiforgeryValidationException: The antiforgery token could not be decrypted.
 ---> System.Security.Cryptography.CryptographicException: The key {5e31d0a7-c6bc-42e5-8fd4-2613a5e05389} was not found in the key ring.
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.DangerousUnprotect(Byte[] protectedData, Boolean ignoreRevocationErrors, Boolean& requiresMigration, Boolean& wasRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.Unprotect(Byte[] protectedData)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgeryTokenSerializer.Deserialize(String serializedToken)
   at Microsoft.AspNetCore.Antiforgery.DefaultAntiforgery.GetCookieTokenDoesNotThrow(HttpContext httpContext)
`

**Comment by gyengus** [comment]
I have same problem.
Screenshot: https://imgur.com/a/oq1F8BM
I got some warn on the console: 
```
zigbee2mqttAssistant    | warn: Zigbee2MqttAssistant.Services.BridgeStateService[0]
zigbee2mqttAssistant    |       Unable to find friendly name from topic smarthome/zigbee2mqtt/kitchen_sensor in entity 0x00158d00025562bc-sensor-humidity.
```
