### ISSUE TITLE
Memory Use (or leak) - seeing 40GB+ RAM use after Z2MA is running for a day or two.

### ISSUE THREAD

**Issue by wixoff** [yllibed/Zigbee2MqttAssistant#32]
I'm running the latest version in Docker.

I don't have much to add, nor do I understand the mechamsim. After 24+ hours, if I run **top** I get 40+ GB virtual memory consumed a "dotnet" process associated with Z2MA and my PC hardly responds to input (because the virutual memeory is too busy thrashing around).  Best bet is to reboot before doing anything else, and even the gentle reboot process is hamstrung by the non-responsive PC and can take 20 minutes.

I recently discovered that killing the Z2MA container brings the system back to life, so reboots are less frequently needed.

Can we take a look at potential memory leaks?  Z2MA is currently unusuable beyond short intervals.

As mentioned, I'm running on Docker on an x86-64 machine with plenty of memory - 32GB.

I can provide addiitonal detail if needed.

**Comment by carldebilly** [comment]
How many devices do you have?  That's very strange.
The process is keeping a state in memory, but it shouldn't leak and it's pretty small even with a huge number of devices.

40GB is clearly a leak. Do you see anything unusual in the logs?

**Comment by carldebilly** [comment]
@all-contributors please add wixoff to bugs

**Comment by wixoff** [comment]
@carldebilly I'll certainly take a look at logs but I'm currently traveling for work so it will be at least a few days.  I don't have too many devices, maybe 20.  I agree it's weird!

**Comment by carldebilly** [comment]
Do you have anything unusual ? I have a setup very similar to yours (using HASS.IO on Ubuntu, also 32GB of memory) and never saw such problem.

**Comment by wixoff** [comment]
OK, so I rebuilt the container (per the README instructions - nothing special) and started it again about six hours ago, and here's the result from the **top** command on my PC just now:

![IMG_8807](https://user-images.githubusercontent.com/945097/65729447-2c439c00-e073-11e9-8d44-1832dec67f34.png)

It's swapping like crazy; the kswap0 process is using 100% cpu and the drive is thrashing.  I kill the container, and all is well again.

**Comment by carldebilly** [comment]
That's definitely a huge memory leak problem...  I'm very perplex because I'm using it a lot and never saw such leak.

We must find what is special on your installation, causing this.

**Comment by james-fry** [comment]
I’m also running on x86-64 w 32gb (hassio on ubuntu on esxi). I’ll keep an eye out for this too

**Comment by carldebilly** [comment]
Please try with latest version... more logging has been activated, maybe you'll see something useful to diagnose this problem.

**Comment by wixoff** [comment]
I will try it again this weekend.  Thanks!

**Comment by wixoff** [comment]
No change with the latest docker pull, I'm sorry to say.  Up to 45.2G after just a few minutes.  The only thing I have in the log is this:

`warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {24d25e74-a34d-42f9-a6fb-b63b97261125} may be persisted to storage in unencrypted form.
Hosting environment: Production
Content root path: /app
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.

Otherwise the log is completely empty.,
`

**Comment by RyuzakiKK** [comment]
I'm facing the same problem.
I was running z1ma for a few minutes and I saw a huge amount of virtual memory usage.

I launched it with:
`docker run -p 8881:80 -e Z2MA_SETTINGS__MQTTSERVER=192.168.10.220 -e Z2MA_SETTINGS__MQTTUSERNAME=user -e Z2MA_SETTINGS__MQTTPASSWORD=mosquitto --restart always carldebilly/zigbee2mqttassistant`

![Screenshot from 2019-10-19 14-06-17](https://user-images.githubusercontent.com/3227973/67144729-5f480c80-f27a-11e9-81cd-313c439d26b3.png)

**Comment by RyuzakiKK** [comment]
I just restarted it and I saw that this 20+ gb of virtual memory usage is reached immediately, it's not something that you need to wait for (so it's not a slow leak over time).

**Comment by carldebilly** [comment]
Oooh.  That's a very strange problem.  Which version of docker are you using? On which OS & CPU ?

I'll soon switch to netcore3.0 & alpine packages. Maybe it will help...

**Comment by RyuzakiKK** [comment]
@carldebilly I'm using Debian Buster, docker version 1.5-2 and the CPU is an Intel i5-8259U.

FYI I'm running multiple docker images and this is the only one with this problem.
Let me know when you update the docker image so that I can test it again.

**Comment by james-fry** [comment]
Im using ubuntu 18.04.2 LTS on ESXI 6.
CPU is a low end XEON.
I am seeing the z2massistant container using ~140Mb using portainer:

![image](https://user-images.githubusercontent.com/5823294/67209184-d0202d80-f40e-11e9-8d73-47cc80a3e1cf.png)

**Comment by carldebilly** [comment]
@james-fry I agree 140Mb is high, but that's more normal than 40GB as reported by @wixoff & @RyuzakiKK.

Next version with netcore3.0 + alpine containers will lower those numbers.

**Comment by james-fry** [comment]
I didnt see it as high.
I was reporting this as normal behaviour.

**Comment by carldebilly** [comment]
@james-fry @RyuzakiKK @wixoff Please try the last "dev" version of Z2MA. It's now using netcore3.0 instead of netcore2.2 and the base image is now alpine (except on ARMv7).

Tell me if you are still experiencing same problems. Thanks!

**Comment by RyuzakiKK** [comment]
@carldebilly it helped a bit. Now It's down from 22gb to 20gb.

![Screenshot from 2019-10-31 10-00-27](https://user-images.githubusercontent.com/3227973/67933095-70bbdd80-fbc5-11e9-8b80-df4129bdacb2.png)

Anyway I'm not sure how serious this might be. It's virtual memory, so it's not really used.
The resident memory (RES column, the real used RAM) is just 77Mb.
And in fact before launching it and after, the effectively used RAM barely changed.

**Comment by james-fry** [comment]
Portainer is telling me the dev container is using <40mb RAM

**Comment by carldebilly** [comment]
Can we consider this as fixed?

**Comment by wixoff** [comment]
I'll be able to check within the next day or so.

**Comment by tayanov** [comment]
+1
webmin show that

root | 19 GiB | dotnet Zigbee2MqttAssistant.dll -- | -- | --

**Comment by wixoff** [comment]
Sorry that it has been a while since I reported in - I'm using podman now instead of docker, but this issue remains unresolved. I get 42.3GB virtual memory use reported by htop.

![Screenshot at 2020-01-11 16:08:25](https://user-images.githubusercontent.com/945097/72210696-5c317680-348d-11ea-805f-2b4296b3282a.png)

**Comment by pgollor** [comment]
Please look ab #195. So ther eis a problem. Every site visit or reload will increase the memory consumption of round about 0.2 MB. Tested on debian 10 and ubuntu 18.04 in a docker container.

**Comment by magpern** [comment]
I did a new memory analysis of Z2MA and I take back what I wrote in #195 . Sure, Z2MA does use more and more memory on each refresh, but every 1 minute, the garbage collection is run and releases that memory. I never get it higher then 170MB. So, I don't think there is a memory leak from Z2MA.
However, I also get 19G of virtual memory for Z2MA on my ubuntu server.
I found this and it seams to be a dotnet thing
[Excessive VM memory consumption on Linux](https://github.com/dotnet/runtime/issues/7740)

**Comment by FutureCow** [comment]
I got the same symptoms:
In portainer is see: 40 MB memory, 10-100 MB Cache
HTOP: VIRT: 19GB RES: 44MB

**Comment by pgollor** [comment]
@magpern I tested it over 10 minutes:
| Memory consumption | time |
|--|--|
| 39 MB | on start |
| 51 MB | after 1 minute with reloads |
| 50 MB | afters 10 minutes |
| 51 MB | after 15 minutes (without any open connection) |

I closed the tab in my browser after 1 minute and wait 10 minutes and more. The garbage collection is not working. We can call it memory leak, bug or by another word but the problem is still alive.
It looks like a programming or conceptual problem.

**Comment by magpern** [comment]
I just installed Zigbee2mqttAssistant on an Orange Pi 3. It has 8GB of disk and 2GB of RAM and it is a 64-bit CPU.
I also see 19.2GB of virtual memory used, but used real memory is not even 500mb
![image](https://user-images.githubusercontent.com/6589760/76577369-58d65d80-64c5-11ea-9339-1319f843cef4.png)

I don't think this is a real issue. It is how .NET looks when running, but it is just how it looks, not the real thing.

and @pgollor your list of used memory. I think it looks ok.
Then Z2MA starts up, it creates all devices in memory and I guess that can account for the 12mb of memory between startup and 1 minute.
Between 1 minute and 15 minutes it looks pretty stable to me?

I propose this issue should be closed
