### ISSUE TITLE
Bitron video 902010/28

### ISSUE THREAD

**Issue by spijkey87** [yllibed/Zigbee2MqttAssistant#331]
The Bitron video 902010/28 is not supported as far as i can see this device the same as the 902010/25 without the power measurement. Can someone please add this to the support list?

**Comment by spijkey87** [comment]
no response?

**Comment by EnesE** [comment]
I think that's an Issue for the zigbee2Mqtt repository and not for the Z2MAssistant repo.

https://github.com/koenkk/zigbee2mqtt

**Comment by spijkey87** [comment]
sorry about that youre right
