### ISSUE TITLE
configure base topic in docker

### ISSUE THREAD

**Issue by dirstel** [yllibed/Zigbee2MqttAssistant#34]
Hi, I'm trying to use version: zigbee2mqttassistant, but I see no option to set the basetopic (different from "zigbee2mqtt"). Is there any config file or something like this which can be mapped outside the container?

**Comment by davekr8** [comment]
Same for me. I use `home/zigbee` for my zigbee devices at home.

**Comment by carldebilly** [comment]
You can set all those values:
https://github.com/yllibed/Zigbee2MqttAssistant#settings

There's a setting called "basetopic" you can set.

**Comment by davekr8** [comment]
And how to pass these parameters inside the docker container? This was the main issue, I think.

**Comment by davekr8** [comment]
Z2MA_SETTINGS__BASETOPIC would be my guess... but who knows...

**Comment by dirstel** [comment]
When using a docker-image, it should be possible to map a config-path outside the container. This allows using different versions of docker containers and eliminates the need of building a new container for altering the configuration. So: is there a path that can be mapped outside? And if so: which?

**Comment by carldebilly** [comment]
@dirstel please open a new issue for that.

**Comment by dirstel** [comment]
> @dirstel please open a new issue for that.

Well, this is my issue. I thought of an answer involving such docker mechanics: exposing the config dir as a volume.
