### ISSUE TITLE
[BUG]Ikea E1745 Tradfri Motion sensor

### ISSUE THREAD

**Issue by synoniem** [yllibed/Zigbee2MqttAssistant#353]
# Describe the bug
I try to connect a Ikea E1745 Tradfri Motion sensor to Zigbee2Mqtt but it does not connect and does not show anything in the log either.

## To Reproduce
With 
1. Enable Allow new devices on the Status tab
2. Press 4 time the reset button on the E1745

**Expected behavior**

Expecting to see a flashing red light on the E1745 and  a new device appearing in HomeAssistant but nothing happens.

## Steps I took to try resolve the problem
With a 10 sec press the E1745 connects to a TRADFRI LED bulb E26/E27 806 lumen
Added some other Tradfri devices like TRADFRI remote control (E1810) and the same TRADFRI LED bulb E26/E27 806 lumen bulb without any problem.

## Installation
 - Version of Zigbee2Mqtt: Current version: 1.16.2.2
 - Version of Zigbee2MqttAssistant:  0.3.157
 - Installation type (HASS.IO, Docker...): HASS.IO
 - Docker version + CPU type (amd64, arm arm64...): arm7

## Pertinent logs
Nothing to see in the log.

**Comment by gitothy** [comment]
Shouldn't this be logged to Zigbee2MQTT not this assistant program?

Issue may be resolved by having your coordinator, this switch and an IKEA signal repeater all within a couple of inches of each other.
