### ISSUE TITLE
[BUG] Only xiaomi devices are visible 

### ISSUE THREAD

**Issue by xeac** [yllibed/Zigbee2MqttAssistant#354]
# Describe the bug
When i try to view all my paired devices, i can see only Xiaomi ones registered. I have also plenty of light switches some flashed with tasmota, others not, but they are not visible in the list and map. Could be that i do something wrong, but they are all working, just not visible in the zigbee2mqtt.
Could you please advise?

thanks

**Comment by jimmyeao** [comment]
tasmota devices need to pointed to a MQTT broker, e.g. mosquitto. Also, Tasmota uses wifi not zigbee, so I wouldn't expect to see them listed in zigbee2mqtt assistant.
