### ISSUE TITLE
Setting the base_topic for the docker image?

### ISSUE THREAD

**Issue by kpmkpm** [yllibed/Zigbee2MqttAssistant#358]
**Is your feature request related to a problem? Please describe.**
I have Home Assistant run on Python virtual environment and  that among with zigbee2mqtt installed on ubuntu 20.04 server. So, the easiest way for me seems to install the docker version of this nice tool.

However, I did not find a way to set base_topic I'm using on zigbee2mqtt (ie. "z2m" not the "zigbee2mqtt"). I tried to "guess" the environment variable to be "Z2MA_SETTINGS__BASE_TOPIC" and tried to set it to z2m, but that did not work.

Is it possible to set the base_topic with the dockerized version? I changed for testing purpose the base topic to zigbee2mqtt and that confirmed the tool works, but I have so many Node Red flows relying to that z2b topic, I would rather not change those flows but tell this tool to use "z2m" instead of "zigbee2mqtt".

**Describe the solution you'd like**
Probably, this is already solved, but I do not know the correct parameter to start the docker image. If not, hope there will be a parameter for base_topic too.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by eiten** [comment]
Try Z2MA_SETTINGS__MQTTPORT

**Comment by carldebilly** [comment]
The correct setting should be `Z2MA_SETTINGS__BASETOPIC`
