### ISSUE TITLE
[BUG]Unable to connect to MQTT server mqtt

### ISSUE THREAD

**Issue by shuttenbah** [yllibed/Zigbee2MqttAssistant#363]
# Describe the bug

## To Reproduce

1. Add the following repository url in HASS.IO:
    https://github.com/yllibed/hassio
2. Install Zigbee2Mq2ttAssistant
3. Configure credentials for MQTT server and press save. 
4. Due to starting i see in log (pic.1):
`warn: Zigbee2MqttAssistant.Services.SettingsService[0]
      Section 'settings' in configuration does not exists. Will use default settings instead.
Hosting environment: Production
Content root path: /app
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to connect to MQTT server mqtt.`
Web UI showing - `Status
Bridge State: offline` (pic.2)

**Expected behavior**

## Steps I took to try resolve the problem

I tried to remove Zigbee2MqttAssistant, Zigbee2Mqtt, MQTT integration and install again. But it did not help. I have same error.

## Screenshots

pic.1
![image](https://user-images.githubusercontent.com/43872302/106891200-11674a00-66f3-11eb-9318-2f6361728c62.png)
pic.2
![image](https://user-images.githubusercontent.com/43872302/106891276-22b05680-66f3-11eb-8a9a-7cd9521aeb32.png)

## Installation
 - Version of Zigbee2Mqtt: Current version: 1.17.1
 - Version of Zigbee2MqttAssistant: Current version: 0.3.157
 - Installation type (HASS.IO, Docker...): OPTION 1 - Installing as `HASS.IO` Add-on
 - Docker version + CPU type (amd64, arm arm64...):Docker version 20.10.2, build 2291f61, armv7l

**Comment by shuttenbah** [comment]
UPD. Seems to settings do not save when i am pressing save.
![image](https://user-images.githubusercontent.com/43872302/106897438-98b8bb80-66fb-11eb-8a71-3fc09ed132c5.png)
![image](https://user-images.githubusercontent.com/43872302/106897596-d1589500-66fb-11eb-93e7-7bcdc185349e.png)
I put settings into appsettings.json and restart container. And Zigbee2Mq2ttAssistant successfully started.
![image](https://user-images.githubusercontent.com/43872302/106897760-082eab00-66fc-11eb-9fdf-c3ba460cee39.png)
![image](https://user-images.githubusercontent.com/43872302/106897841-24cae300-66fc-11eb-8b09-01145f52b4a8.png)
![image](https://user-images.githubusercontent.com/43872302/106897886-32806880-66fc-11eb-87ed-4080be401c16.png)
But after restart add-on settings empty again.

**Comment by carldebilly** [comment]
The user configuration coming from HASS.IO can be found in `/data/options.json`.

In Z2MA, it's configured there: https://github.com/yllibed/Zigbee2MqttAssistant/blob/7b1877a40d9d37c5a18e33632ecf85e6eda09a95/Zigbee2MqttAssistant/Program.cs#L22

**Comment by shuttenbah** [comment]
Thank you for replying. I insert setting and press save:
![image](https://user-images.githubusercontent.com/43872302/106906068-79bf2700-6705-11eb-9f3a-e8a6b3550c95.png)
But /data/options.json is still empty:
![image](https://user-images.githubusercontent.com/43872302/106906357-bee35900-6705-11eb-9f9c-a719dbfc3d7f.png)

**Comment by carldebilly** [comment]
To be honest, I don't know what this could be, but for sure, it's a HASS.IO issue, not in Z2MA.  Do you think it's something caused by a recent version of HASS.IO?

**Comment by shuttenbah** [comment]
it is very likely. I updated hass.io to 2021.2.0 yesterday

**Comment by carldebilly** [comment]
I'll upgrade my lab to test this...

**Comment by carldebilly** [comment]
It works on my Raspberry Pi 3 with the latest version of HASS OS :-|

**Comment by LA-chel** [comment]
The same problem: core-2021.2.1, supervisor-2021.02.4, Docker version 20.10.3

**Comment by jirmjos** [comment]
Same Issue her, from this morning after upgrade my hassio supervisor to 115.2., zigbee2mqttassistant unable to start and no devices in it.
Raise error bellow , an my parameters ar the same as before when was working for  motnths without issues.
I unistall and install dev-branch with same error. So some are broken to this addon.

warn: Zigbee2MqttAssistant.Services.SettingsService[0]
      Section 'settings' in configuration does not exists. Will use default settings instead.
Hosting environment: Production
Content root path: /app
Now listening on: http://[::]:80
Application started. Press Ctrl+C to shut down.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to connect to MQTT server mqtt.

**Comment by sander816** [comment]
yes, same error here, updated and now zigbee2mqtt assistant is offline

**Comment by user514** [comment]
Today I notice the same problem. 'zigbee2mqtt' working ok (devices reachable, etc), but I noticed entering 'zigbee2mqtt assistant webui' has no devices on the list.

  Same error: Unable to connect to MQTT server mqtt in the assistant log. Updated to 2021.02.xx recently... but not sure when 'assistant' list of devices dissapear.

**Comment by MageMaster87** [comment]
On my Raspberry Pi 4, after updating to Home Assistant 2021.2.2 also stopped working, there was no problem before update. Everything still works through mqtt but in zigbee2mqttassistant I don't have any device in list and bridge state is offline

Same error in log: "Section 'settings' in configuration does not exists. Will use default settings instead."

**Comment by paranojk** [comment]
Same here. HA Core made a lot of security updates in release 2021.1.5. They are mentioning something about directory traversal, but I need to do some more reading.
https://www.home-assistant.io/blog/2021/01/23/security-disclosure2/

**Comment by solsv** [comment]
I'm experiencing the same issue. Looking at the supervisor logs, it appears as though the settings are not getting passed to Z2MA for some reason:
```
21-02-09 23:42:00 INFO (SyncWorker_1) [supervisor.docker.interface] Downloading docker image carldebilly/zigbee2mqttassistant with tag 0.3.157.
21-02-09 23:42:06 INFO (MainThread) [supervisor.addons] Add-on '806b11b5_zigbee2mqttassistant' successfully installed
21-02-09 23:42:48 WARNING (MainThread) [supervisor.addons.options] Unknown options settings
21-02-09 23:43:34 WARNING (MainThread) [supervisor.addons.options] Unknown options settings
21-02-09 23:43:34 WARNING (MainThread) [supervisor.addons.options] Unknown options settings
21-02-09 23:43:37 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on carldebilly/zigbee2mqttassistant with version 172
```

**Comment by paranojk** [comment]
Quick update - I've just found bug and solution. `config.json` in the repository is missing schema (it is set to `schema: false`). After trying on my repo and adding schema everything is working again :-)

Added pull request https://github.com/yllibed/hassio/pull/6

**Comment by solsv** [comment]
@paranojk's solution is working for me.

**Comment by shuttenbah** [comment]
@paranojk Hi, it works. Great. Nice work.

**Comment by diagonali** [comment]
> Quick update - I've just found bug and solution. `config.json` in the repository is missing schema (it is set to `schema: false`). After trying on my repo and adding schema everything is working again :-)
> 
> Added pull request [yllibed/hassio#6](https://github.com/yllibed/hassio/pull/6)

Thanks for info. Where is the config.json you mention and what do we need to change?

**Comment by paranojk** [comment]
@diagonali: file affected is https://github.com/yllibed/hassio/blob/master/zigbee2mqttassistant/config.json - it is used for repo configuration in HA. You could temporary use my fork with fix https://github.com/paranojk/hassio until it's merged with main repo.

**Comment by jirmjos** [comment]
Thank you @paranojk, with your repo working like a champ !

**Comment by carldebilly** [comment]
Fixed by https://github.com/yllibed/hassio/pull/6

**Comment by Pawel128** [comment]
I also have this problem. I believe that your solution is very good, but I don't know how to apply it, what to do with the config.json file? put it somewhere? please give me a hint, thank you

**Comment by solsv** [comment]
@Pawel128 the fix is now incorporated into this repo. Try reinstalling and it should work.
