### ISSUE TITLE
Zigbee2mqtt dev branch: coordinitor shows up in GUI but with error

### ISSUE THREAD

**Issue by neographikal** [yllibed/Zigbee2MqttAssistant#48]
Because of problems with my Tradfri bulbs I upgraded to the latest version of the dev branch of Zigbee2mqtt. The coordinator now shows up in the device list, this is new and not yet recognized by zigbee2mqttassistant:

![image](https://user-images.githubusercontent.com/2643715/65534219-4e1c1200-deff-11e9-8337-378c11992ae0.png)

**Comment by carldebilly** [comment]
Ooohhh  that's interesting. It's just a display error: the GUI doesn't know what to do with it.

I'll add a support for this.  Thanks for reporting!

@all-contributors please add neographikal to bug

**Comment by carldebilly** [comment]
@all-contributors please add neographikal to bugs

**Comment by carldebilly** [comment]
Fixed in latest version `0.2.0-dev.94`!

Please test it and come back if there's any problem remaining.
