### ISSUE TITLE
ARM compatibility?

### ISSUE THREAD

**Issue by muuuh** [yllibed/Zigbee2MqttAssistant#5]
Hello,

I'm using a Raspberry 4 with docker. Is this compatible?

Best regards,

**Comment by HydrelioxGitHub** [comment]
Same question here. I'm using Home Assistant on Raspberry Pi 3.

**Comment by carldebilly** [comment]
It would be pretty easy to add more platforms: I'll try to add it soon.

**Comment by carldebilly** [comment]
A new version has been published to support Raspberry Pi... please test it!!

@muuuh @HydrelioxGitHub
