### ISSUE TITLE
how to get rid of various warnings

### ISSUE THREAD

**Issue by remb0** [yllibed/Zigbee2MqttAssistant#52]
I suspect I have some old devices in my mqtt database that are made by a battery script. and a webcam integration that I can't delete.
Zigbee2MqttAssistant gave several warnings, what's the right way to get rid of this?

Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to qualify a message received on topic 'homeassistant/sensor/zigbee_knop_trapgat_battery/state'.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to qualify a message received on topic 'homeassistant/sensor/zigbee_knop_trapgat_battery/attributes'.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to qualify a message received on topic 'homeassistant/sensor/switch_158d0001a5e296_battery/config'.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to qualify a message received on topic 'homeassistant/sensor/switch_158d0001a5e296_battery/state'.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to qualify a message received on topic 'homeassistant/sensor/switch_158d0001a5e296_battery/attributes'.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to qualify a message received on topic 'homeassistant/sensor/unknown_node_41_battery/config'.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to qualify a message received on topic 'homeassistant/sensor/unknown_node_41_battery/state'.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to qualify a message received on topic 'homeassistant/sensor/unknown_node_41_battery/attributes'.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to qualify a message received on topic 'homeassistant/sensor/wall_switch_both_158d00027c1640_battery/config'.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to qualify a message received on topic 'homeassistant/sensor/wall_switch_both_158d00027c1640_battery/state'.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to qualify a message received on topic 'homeassistant/sensor/wall_switch_both_158d00027c1640_battery/attributes'.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to qualify a message received on topic 'homeassistant/sensor/wall_switch_left_158d00027c1640_battery/config'.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to qualify a message received on topic 'homeassistant/sensor/wall_switch_left_158d00027c1640_battery/state'.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to qualify a message received on topic 'homeassistant/sensor/wall_switch_left_158d00027c1640_battery/attributes'.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to qualify a message received on topic 'homeassistant/sensor/wall_switch_right_158d00027c1640_battery/config'.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to qualify a message received on topic 'homeassistant/sensor/wall_switch_right_158d00027c1640_battery/state'.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to qualify a message received on topic 'homeassistant/sensor/wall_switch_right_158d00027c1640_battery/attributes'.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to qualify a message received on topic 'homeassistant/sensor/0x00158d0001a5e296_click_battery/config'.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to qualify a message received on topic 'homeassistant/sensor/0x00158d0001a5e296_click_battery/state'.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to qualify a message received on topic 'homeassistant/sensor/0x00158d0001a5e296_click_battery/attributes'.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to qualify a message received on topic 'homeassistant/sensor/0x00158d0001a5e296_linkquality_battery/state'.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to qualify a message received on topic 'homeassistant/sensor/0x00158d0001a5e296_linkquality_battery/attributes'.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to qualify a message received on topic 'homeassistant/sensor/0x000b57fffeb207b2_action_battery/config'.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to qualify a message received on topic 'homeassistant/sensor/0x000b57fffeb207b2_action_battery/state'.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to qualify a message received on topic 'homeassistant/sensor/0x000b57fffeb207b2_action_battery/attributes'.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to qualify a message received on topic 'homeassistant/sensor/0x000b57fffeb207b2_linkquality_battery/config'.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to qualify a message received on topic 'homeassistant/sensor/0x000b57fffeb207b2_linkquality_battery/state'.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to qualify a message received on topic 'homeassistant/sensor/0x000b57fffeb207b2_linkquality_battery/attributes'.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to qualify a message received on topic 'homeassistant/sensor/0x00158d000222de95_occupancy_battery/config'.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to qualify a message received on topic 'homeassistant/sensor/0x00158d000222de95_occupancy_battery/state'.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to qualify a message received on topic 'homeassistant/sensor/0x00158d000222de95_occupancy_battery/attributes'.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to qualify a message received on topic 'homeassistant/sensor/0x00158d000222de95_illuminance_battery/config'.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to qualify a message received on topic 'homeassistant/sensor/0x00158d000222de95_illuminance_battery/state'.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to qualify a message received on topic 'homeassistant/sensor/0x00158d000222de95_illuminance_battery/attributes'.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to qualify a message received on topic 'homeassistant/sensor/0x00158d000222de95_linkquality_battery/config'.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to qualify a message received on topic 'homeassistant/sensor/0x00158d000222de95_linkquality_battery/state'.
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to qualify a message received on topic 'homeassistant/sensor/0x00158d000222de95_linkquality_battery/attributes'.
warn: Zigbee2MqttAssistant.Services.BridgeStateService[0]
      Unable to find friendly name from topic myhome/dafang/motion in entity dafang-binary_sensor-motion.
warn: Zigbee2MqttAssistant.Services.BridgeStateService[0]
      Unable to find friendly name from topic myhome/dafang/motion/detection in entity dafang-switch-motion_detection.
warn: Zigbee2MqttAssistant.Services.BridgeStateService[0]
      Unable to find friendly name from topic myhome/dafang/motion/send_mail in entity dafang-switch-motion_send_mail.
warn: Zigbee2MqttAssistant.Services.BridgeStateService[0]
      Unable to find friendly name from topic myhome/dafang/motion/tracking in entity dafang-switch-motion_tracking.
warn: Zigbee2MqttAssistant.Services.BridgeStateService[0]
      Unable to find friendly name from topic myhome/dafang/leds/blue in entity dafang-switch-blue_led.
warn: Zigbee2MqttAssistant.Services.BridgeStateService[0]
      Unable to find friendly name from topic myhome/dafang/leds/yellow in entity dafang-switch-yellow_led.
warn: Zigbee2MqttAssistant.Services.BridgeStateService[0]
      Unable to find friendly name from topic myhome/dafang/leds/ir in entity dafang-switch-ir_led.
warn: Zigbee2MqttAssistant.Services.BridgeStateService[0]
      Unable to find friendly name from topic myhome/dafang/ir_cut in entity dafang-switch-ir_cut.
warn: Zigbee2MqttAssistant.Services.BridgeStateService[0]
      Unable to find friendly name from topic myhome/dafang/night_mode in entity dafang-switch-night_mode.
warn: Zigbee2MqttAssistant.Services.BridgeStateService[0]
      Unable to find friendly name from topic myhome/dafang/night_mode/auto in entity dafang-switch-auto_night_mode.
warn: Zigbee2MqttAssistant.Services.BridgeStateService[0]
      Unable to find friendly name from topic myhome/dafang/rtsp_h264_server in entity dafang-switch-rtsp_h264_server.
warn: Zigbee2MqttAssistant.Services.BridgeStateService[0]
      Unable to find friendly name from topic myhome/dafang/rtsp_mjpeg_server in entity dafang-switch-rtsp_mjpeg_server.
warn: Zigbee2MqttAssistant.Services.BridgeStateService[0]
      Unable to find friendly name from topic myhome/dafang/motion/send_telegram in entity dafang-switch-motion_send_telegram.

**Comment by carldebilly** [comment]
You can eiter fix them in code (I'll accept the PR) or ask me to fix them :-)

**Comment by remb0** [comment]
I really don't know how to fix. But is this something from in my setup or ? can you tell me how to fix or are you willing to fix it?

**Comment by carldebilly** [comment]
Some of those warnings are removed in the latest version. Please confirm.  I think the only ones remaining are those ending with `/attributes`... Am I correct?

**Comment by carldebilly** [comment]
The latest version should remove them all.  Please reopen this issue if you have any new problem.
