### ISSUE TITLE
MQTT server option only supports IP address? 

### ISSUE THREAD

**Issue by CodeFinder2** [yllibed/Zigbee2MqttAssistant#57]
Hi! First of all, great work!

I've realized that the 'mqttserver' option only supports an IP address, not a hostname or even a port number (also IP:PORT is not working). Is it normal / known or is it a problem on my side? 🙈

Thanks!

**Comment by carldebilly** [comment]
As defined in the settings <https://github.com/yllibed/Zigbee2MqttAssistant#settings>, the port is defined using the `MqttPort`. The default value will depend if you're using the _secured_ connection or not.

You can put a hostname in the `MqttServer` setting, it should be resolved using the ambiant DNS. On HASS.IO or Docker, you can resolve directly on the container name. If you're using the official Mosquitto with HASS.IO, you can use `addon_core_mosquitto` as `MqttServer`.
