### ISSUE TITLE
Duplicate links between nodes in map

### ISSUE THREAD

**Issue by dr1rrb** [yllibed/Zigbee2MqttAssistant#61]
Some links are duplicated in the map:
![image](https://user-images.githubusercontent.com/8635919/66422584-efaf6300-e9d7-11e9-9224-a001a2fa2c0b.png)

It seems that it's only between routers (Is there a link from router A to router B and another one from B to A in the object model ?)

**Comment by carldebilly** [comment]
Did you try the new version? Do you still think dual links are problematics? If yes please reopen this issue.
