### ISSUE TITLE
Switch to alpine containers + dotnet 3.0

### ISSUE THREAD

**Issue by danieledwardgeorgehitchcock** [yllibed/Zigbee2MqttAssistant#66]
I have reviewed the code base and the docker files for this project - there is nothing apparent that would require a full-fat Debian distro.

Size-wise, the Debian image is around 300mb whereas the Alpine equivalent is around 20mb.

While this would not have any benefits on performance, it would be beneficial to keep the image as lean and bloat-free as possible

**Comment by carldebilly** [comment]
You're 100% right! I know that, it's already in the plan to migrate to both dotnet 3.0 (which will also solve a problem on the build server requiring the code to be build on Windows only) and use alpine containers.

There's already a PR for that (#8) but it was for dotnet 2.2.

Going to dotnet 3.0 will also bring the arm64 target, which is a problem on the HASS.IO installed on a HASSOS/arm64 using the aarch64 cpu.

**Comment by carldebilly** [comment]
The "dev" version is now using alpine containers + netcore 3.0!

@danieledwardgeorgehitchcock what do you think? ;-)
