### ISSUE TITLE
Configure what port it exposes the interface on

### ISSUE THREAD

**Issue by timdonovanuk** [yllibed/Zigbee2MqttAssistant#67]
Please...default to 80 but at least make it configurable.

**Comment by carldebilly** [comment]
Which option are you using?

You can simply set the following environment variable:
```
ASPNETCORE_URLS=https://*:5000
```

Example:
```
> docker run -it -p 5000:5000 -e ASPNETCORE_URLS=http://*:5000 carldebilly/zigbee2mqttassistant
Hosting environment: Production
Content root path: C:\app
Now listening on: http://[::]:5000
Application started. Press Ctrl+C to shut down.
```

# BUT.... It's docker!
If you are using the _docker_ version, you just need to map the port to what you want!

Here's an example to start on port #8880:
```
> docker run -p 8880:80 carldebilly/zigbee2mqttassistant
```

**Comment by carldebilly** [comment]
By the way, if you want https protocol instead, you'll need to follow instructions there:
github.com/dotnet/dotnet-docker/blob/master/samples/aspnetapp/aspnetcore-docker-https.md

To resume variables:
* `ASPNETCORE_URLS="https://*:5000"` to activate https on port tcp/5000
* `ASPNETCORE_Kestrel__Certificates__Default__Path="/https/cert.pfx"`  assuming you mount a `/https` volume containing your certificate
* `ASPNETCORE_Kestrel__Certificates__Default__Password="mypw"` for the password of your `.pfx` file, if any
