### ISSUE TITLE
Allow ability to configure base MQTT topic

### ISSUE THREAD

**Issue by philhawthorne** [yllibed/Zigbee2MqttAssistant#7]
Hi @yllibed 

I am running two instances of Zigbee2mqtt in my home, which means they are running via two MQTT base topics.

It would be good to be able to set the MQTT base_topic to match the one used in Zigbee2MQTT's config.

**Comment by philhawthorne** [comment]
Actually I just saw this as available in the settings. Just to clarify, is this available for Docker via the environment variables?

**Comment by carldebilly** [comment]
Yes it is.  All settings can be set using the following syntax:
`Z2MA_SETTINGS__<fieldnamename>`

And those variables are uppercase by convention, but the runtime is case insensitive.

Feel free to reopen this issue if you're still having problems.

**Comment by philhawthorne** [comment]
Great! I'll give this a shot

**Comment by carldebilly** [comment]
@philhawthorne did it work?

**Comment by philhawthorne** [comment]
@carldebilly I think it did, but unfortunately I've moved on from Zigbee2mqtt now so I can't verify

**Comment by carldebilly** [comment]
Ok.
