### ISSUE TITLE
Allow connecting to MQTT Brokers with Self Signed Certificates

### ISSUE THREAD

**Issue by RafhaanShah** [yllibed/Zigbee2MqttAssistant#81]
Zigbee2MqttAssistant will not connect to an MQTT broker on the local network using TLS as it complains that the certificate is for "some.domain.com" but it is connecting to a local IP (eg: 192.168.1.10).

The exact error is: "The remote certificate is invalid according to the validation procedure"

A similar option on the Zigbee2Mqtt config is "reject_unauthorized" which allows it to work with the MQTT broker. The option in the Home Assistant MQTT broker configuration is: "tls_insecure"

Would be nice if we could get a similar option with this assistant!

**Comment by carldebilly** [comment]
@all-contributors please add RafhaanShah to ideas

**Comment by carldebilly** [comment]
Fixed!  Done with PR #82.  Please try it!

To use it, you just need to replace the `true` by `"insecure"` for the _MqttSecure_ setting.

Note: the fix is present in Zigbee2MqttAssistant v0.2.0-dev.150+

**Comment by RafhaanShah** [comment]
That was super quick, thanks a lot for making the change and adding me to the contributors!

**Comment by RafhaanShah** [comment]
Hey, not sure if I'm mis-configuring something but I still seem to be getting the same error, I'm using v0.3.83 of the add-on, here's my config:

`{
  "settings": {
    "mqttserver": "addon_core_mosquitto",
    "mqttusername": "****",
    "mqttpassword": "****",
    "mqttsecure": "insecure",
    "mqttport": 8883,
    "basetopic": "zigbee2mqtt",
    "HomeAssistantDiscoveryBaseTopic": "homeassistant",
    "lowbatterythreshold": 25
  }
}`

**Comment by kruemelro** [comment]
I have the same error. I run it as a Docker Container and configured it with:

-e Z2MA_SETTINGS__MQTTSECURE=INSECURE

But it gives me the same error as mentioned by Rafhaan above.

**Comment by carldebilly** [comment]
Should work. Please try something...

This configuration should be case insensitive, but maybe it's now.  Please try the following:
``` shell
-e Z2MA_SETTINGS__MQTTSECURE=Insecure
```

**Comment by kruemelro** [comment]
It seems case sensitive is not the problem. It dont make a difference if i start with:
- INSECURE
- Insecure
- insecure

The Error only changes wenn i start with Z2MA_SETTINGS__MQTTSECURE=false. True and Insecure produces the same error.

**Comment by carldebilly** [comment]
Do you have an easy way to help me to reproduce this problem? Could be a docker-compose file, anyway...

**Comment by kruemelro** [comment]
No cause you have to generate all the certificate stuff. But i've found this:
[https://github.com/mchestr/Secure-MQTT-Docker](https://github.com/mchestr/Secure-MQTT-Docker)

I think its the fastest way to get a tls enabled mqtt up and running

**Comment by carldebilly** [comment]
To develop it I tried `https://cloudmqtt.com/` by using just the IP address on the TLS port (instead of the correct name) to get a TLS negociation error.

Ok let me try this. It will have time later this week for that.

**Comment by RafhaanShah** [comment]
Seems to be working now with "mqttsecure": "insecure". Thanks!

**Comment by Turiok** [comment]
Hi,

I tried this your example with the last dev version for hass. 0.341. But I always have the error :
```
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to connect to MQTT server addon_core_mosquitto.
MQTTnet.Exceptions.MqttCommunicationException: The remote certificate is invalid according to the validation procedure.
```

How do you specify the trusted ca?
