### ISSUE TITLE
Unable to connect to MQTT via Docker

### ISSUE THREAD

**Issue by philhawthorne** [yllibed/Zigbee2MqttAssistant#9]
I'm attempting to use this on my Synology NAS. 

With the default `docker run` command, it uses an internal IP address for itself. Which means I can't use `127.0.0.1` to connect to the MQTT server running in a different container.

My MQTT container is set using `--net=host` to give it full network access. 

If I set my MQTT address to the IP address of my NAS ie `192.168.1.x` then I receive the following error:

```
warn: Zigbee2MqttAssistant.Services.MqttConnectionService[0]
      Unable to connect to MQTT server 192.168.1.3.
MQTTnet.Exceptions.MqttCommunicationException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'. ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.<>c.<ConnectAsync>b__274_0(IAsyncResult iar)
--- End of stack trace from previous location where exception was thrown ---
   at MQTTnet.Implementations.MqttTcpChannel.ConnectAsync(CancellationToken cancellationToken)
   at MQTTnet.Internal.MqttTaskTimeout.WaitAsync(Func`2 action, TimeSpan timeout, CancellationToken cancellationToken)
   at MQTTnet.Adapter.MqttChannelAdapter.ConnectAsync(TimeSpan timeout, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at MQTTnet.Adapter.MqttChannelAdapter.WrapException(Exception exception)
   at MQTTnet.Adapter.MqttChannelAdapter.ConnectAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(IMqttClientOptions options, CancellationToken cancellationToken)
   at MQTTnet.Client.MqttClient.ConnectAsync(IMqttClientOptions options, CancellationToken cancellationToken)
   at MQTTnet.Extensions.ManagedClient.ManagedMqttClient.ReconnectIfRequiredAsync()
warn: Microsoft.AspNetCore.HttpsPolicy.HttpsRedirectionMiddleware[3]
      Failed to determine the https port for redirect.

```

(I am not using HTTPS or SSL for MQTT)

If I set the container to use `--net=host`, the container fails to start because port 80 is already used by another application.

It would be good to be able to specify the port the service should use, so that `--net=host` can be supported as well.

**Comment by krasnoukhov** [comment]
It worked for me when I gave it the "public" ip of the host that's running mqtt. For example: `Z2MA_SETTINGS__MQTTSERVER=192.168.1.2`

**Comment by carldebilly** [comment]
That's odd.

No tests has been done right now with `--net=host` because it's not required by this software to have a direct access to your network.

Let's me try it on my side.

I'm glad it's working on Synology NAS ;-).  What is the CPU architecture ? Intel or ARM ?

**Comment by carldebilly** [comment]
That's a _docker_ limitation, not a problem with Zigbee2Mqtt.

When using the address `127.0.0.1`, you're resolving this in your _container namespace_, not on the host itself, which is elsewhere.

You can name your containers using `--hostname mqttserver` and use this name instead to read your MQTT server.

**Comment by philhawthorne** [comment]
Hmm don't think this should be closed. This is still very much a limitation of *this* container. 

Your solution requires me to go ahead and update all of my other containers and internal DNS, because I can't use the host network with this container. The only reason I can't use the host network, is because I can't change the HTTP port from 80 to something else.

Unfortunately Docker runs on many types of systems. And sometimes there are reasons why assigning a hostname to a container can't work (one of those is when the MQTT container is using the host network for another reason entirely)

So for now the "fix" is to go ahead and update all my other Docker containers to point to the MQTT hostname. Seems quite the wrong way to do it.

**Comment by carldebilly** [comment]
@philhawthorne Did you try with latest version, now using the alpine images?

**Comment by philhawthorne** [comment]
@carldebilly is it possible to change the HTTP port this service is exposed on from something _other_ than 80?

Right now I can't use `--net=host` for this container because port 80 is used by the Synology Admin Panel. If I can tel this service to be exposed on another port, then I can use `--net=host` to expose this to my network, and not conflict with Synology.

**Comment by carldebilly** [comment]
Yep it is possible. As described in another issue #67, you can use the following method:

To set port tcp/5000 for http, use the following environment variable:
```
ASPNETCORE_URLS=http://*:5000
```

Please close the issue if it fixes your problem :-).

**Comment by philhawthorne** [comment]
That did it!

Thanks
