### ISSUE TITLE
Network graph not right

### ISSUE THREAD

**Issue by neographikal** [yllibed/Zigbee2MqttAssistant#93]
Output from z2mqtta:

![graph](https://user-images.githubusercontent.com/2643715/67639633-70d08a80-f8f2-11e9-8253-cc590709b46e.PNG)

Arrows not visible, network not really visible. Out from https://dreampuf.github.io/ based on output from mqtt:

[graphviz.zip](https://github.com/yllibed/Zigbee2MqttAssistant/files/3776258/graphviz.zip)

Much more comprehensive and insightful :)

**Comment by carldebilly** [comment]
When arrows are not there it means there's no network information yet.  You can launch a manual scan.

**Comment by neographikal** [comment]
It's kind of strange, I generated these two very close together. Will try again this evening

**Comment by carldebilly** [comment]
Check if there's something suspicious in the logs...
