### ISSUE TITLE
hassio addon - zigbee2mqttassistant-aarch64 - no network map?

### ISSUE THREAD

**Issue by pejotigrek** [yllibed/Zigbee2MqttAssistant#95]
I'm using HASSIO install on RPi3; zigbee2mqttAssistant installed via addons, aarch64 version.
is it normal that I don't see the "Map" option in the menu of the assistant?
my brother's device, with regular [non aarch64] version displays network map with no problem.

**Comment by carldebilly** [comment]
Please try to install the `dev` version of zigbee2mqtt assistant.  The publication of the `aarch64` version what a big patch than should be resolved by the yesterday's `dev` build.

I didn't tested it yet... so if you can test it for me it would be very appreciated!

**Comment by pejotigrek** [comment]
dev branch, version 0.3.89 installed & working.
map is showing in the options and displays my zigbee devices correctly :)

**Comment by carldebilly** [comment]
Great!  Wow, that means I can remove  the old `-aarch64` build which is not required anymore.

Thanks for testing!
